@extends('layouts.app', ['title'=>'جزئیات تسویه'])
@push('head')<link rel="stylesheet" href="{{ asset('css/stage10-settlements.css').'?v=0.22.0' }}">@endpush
@section('content')
<div class="ensha-page-heading"><div><span class="ensha-eyebrow">{{ $settlement->settlement_number }}</span><h2>تسویه {{ $settlement->counselor?->display_name }}</h2><p>دوره <span data-jalali-date="{{ $settlement->period_start?->format('Y-m-d') }}">{{ $settlement->period_start?->format('Y-m-d') }}</span> تا <span data-jalali-date="{{ $settlement->period_end?->format('Y-m-d') }}">{{ $settlement->period_end?->format('Y-m-d') }}</span></p></div><a class="ensha-secondary-btn" href="{{ route('settlements.index') }}">بازگشت</a></div>
<div class="settlement-summary five"><div><span>وصول دوره</span><strong>{{ number_format($settlement->gross_collected_amount) }}</strong></div><div><span>سهم مرکز</span><strong>{{ number_format($settlement->centre_share_amount) }}</strong></div><div><span>سهم مشاور</span><strong>{{ number_format($settlement->counselor_share_amount) }}</strong></div><div><span>کسورات / پاداش</span><strong>{{ number_format($settlement->deductions_amount) }} / {{ number_format($settlement->bonuses_amount) }}</strong></div><div><span>قابل پرداخت</span><strong>{{ number_format($settlement->payable_amount) }}</strong></div></div>
<section class="ensha-card settlement-section"><div class="settlement-head"><div><h3>گردش کار</h3><p>وضعیت فعلی: <span class="settlement-badge {{ $settlement->status }}">{{ ['draft'=>'پیش‌نویس','approved'=>'تأییدشده','paid'=>'پرداخت‌شده','cancelled'=>'لغوشده'][$settlement->status] }}</span></p></div></div><div class="settlement-actions">
@if($settlement->status==='draft' && auth()->user()->hasPermission('settlements.approve'))<form method="POST" action="{{ route('settlements.approve',$settlement) }}">@csrf<button class="ensha-primary-btn">تأیید تسویه</button></form>@endif
@if($settlement->status==='approved' && auth()->user()->hasPermission('settlements.pay'))<form method="POST" action="{{ route('settlements.pay',$settlement) }}" class="inline-form">@csrf<input name="payment_reference" placeholder="شماره پیگیری پرداخت" required maxlength="120"><button class="ensha-primary-btn">ثبت پرداخت</button></form>@endif
@if($settlement->status==='draft' && auth()->user()->hasPermission('settlements.manage'))<form method="POST" action="{{ route('settlements.cancel',$settlement) }}" class="inline-form">@csrf<input name="reason" placeholder="علت لغو" required maxlength="2000"><button class="ensha-danger-btn">لغو پیش‌نویس</button></form>@endif
</div>@if($settlement->payment_reference)<p>شماره پیگیری: <b dir="ltr">{{ $settlement->payment_reference }}</b></p>@endif</section>
<section class="ensha-card settlement-section"><div class="settlement-head"><div><h3>اقلام جلسات</h3><p>اعداد این جدول Snapshot شده و غیرقابل ویرایش‌اند.</p></div></div><div class="overflow-x-auto"><table class="ensha-table"><thead><tr><th>نوبت</th><th>مراجع</th><th>موضوع</th><th>وصول منظورشده</th><th>سهم مرکز</th><th>سهم مشاور</th></tr></thead><tbody>@foreach($settlement->items as $item)<tr><td><a href="{{ route('appointments.show',$item->appointment) }}" dir="ltr">{{ $item->appointment?->appointment_number }}</a></td><td>{{ $item->appointment?->client?->user?->display_name }}</td><td>{{ $item->appointment?->topic?->name }}</td><td>{{ number_format($item->collected_amount) }}</td><td>{{ number_format($item->centre_share_amount) }}</td><td>{{ number_format($item->counselor_share_amount) }}</td></tr>@endforeach</tbody></table></div></section>
@if($settlement->adjustments->isNotEmpty())<section class="ensha-card settlement-section"><h3>تعدیلات</h3><ul class="settlement-adjustments">@foreach($settlement->adjustments as $adjustment)<li><span>{{ $adjustment->title }}</span><b>{{ $adjustment->kind==='deduction'?'-':'+' }}{{ number_format($adjustment->amount) }} ریال</b></li>@endforeach</ul></section>@endif
@endsection
@push('scripts')<script src="{{ asset('js/stage07-clinical.js').'?v=0.19.0' }}"></script>@endpush
