@extends('layouts.app', ['title'=>'تقویم منشی'])
@push('head')<link rel="stylesheet" href="{{ asset('css/secretary-calendar.css').'?v=0.16.0' }}">@endpush
@section('content')
@include('appointments.partials.nav')
<div class="ensha-page-heading"><div><span class="ensha-eyebrow">Stage 04</span><h2>تقویم Outlook منشی</h2><p>نمای برنامهٔ مشاوران؛ جابه‌جایی نوبت فقط به اسلات آزاد و با کنترل تداخل انجام می‌شود.</p></div>@if(auth()->user()->hasPermission('appointments.manage'))<button class="ensha-primary-btn" data-calendar-new>ثبت نوبت در تقویم</button>@endif</div>
<section class="ensha-card secretary-calendar-card" id="secretary-calendar"
    data-events-url="{{ route('appointments.calendar.api.events') }}" data-slots-url="{{ route('appointments.calendar.api.available-slots') }}" data-store-url="{{ route('appointments.calendar.api.store') }}" data-update-url="{{ url('/appointments/calendar/api/events') }}" data-csrf="{{ csrf_token() }}" data-can-manage="{{ auth()->user()->hasPermission('appointments.manage') ? 1 : 0 }}">
  <div class="secretary-toolbar">
    <div class="secretary-toolbar-group"><button type="button" class="ensha-secondary-btn" data-calendar-prev>‹</button><button type="button" class="ensha-secondary-btn" data-calendar-today>امروز</button><button type="button" class="ensha-secondary-btn" data-calendar-next>›</button><strong data-calendar-title></strong></div>
    <div class="secretary-toolbar-group"><select class="kt-input" data-calendar-view><option value="day">روز</option><option value="week" selected>هفته</option><option value="month">ماه</option></select><select class="kt-input" data-calendar-counselor><option value="">همه مشاوران</option>@foreach($counselors as $counselor)<option value="{{ $counselor->id }}">{{ $counselor->display_name }}</option>@endforeach</select><select class="kt-input" data-calendar-topic><option value="">همه خدمات</option>@foreach($topics as $topic)<option value="{{ $topic->id }}">{{ $topic->name }}</option>@endforeach</select><select class="kt-input" data-calendar-status><option value="">همه وضعیت‌ها</option>@foreach(['pending'=>'در انتظار','confirmed'=>'تأییدشده','arrived'=>'حاضر','in_session'=>'در جلسه','completed'=>'تکمیل‌شده','cancelled'=>'لغوشده','no_show'=>'عدم مراجعه'] as $key=>$label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></div>
  </div>
  <div class="secretary-calendar-legend"><span><i class="pending"></i>در انتظار</span><span><i class="confirmed"></i>تأیید</span><span><i class="arrived"></i>حاضر</span><span><i class="in_session"></i>در جلسه</span><span><i class="completed"></i>تکمیل</span><span><i class="cancelled"></i>لغو</span></div>
  <div class="secretary-calendar-loading" data-calendar-loading>در حال بارگذاری تقویم…</div><div class="secretary-calendar-grid" data-calendar-grid></div>
</section>
@if(auth()->user()->hasPermission('appointments.manage'))
<div class="secretary-modal" data-calendar-modal hidden><div class="secretary-modal-backdrop" data-calendar-close></div><form class="secretary-modal-box" data-calendar-form><div class="secretary-modal-title"><strong>ثبت نوبت از تقویم</strong><button type="button" class="kt-btn kt-btn-sm kt-btn-icon" data-calendar-close>×</button></div><p class="text-2sm text-muted-foreground">ابتدا مراجع و اسلات آزاد را انتخاب کنید؛ رزرو نهایی در سرور کنترل می‌شود.</p><label>مراجع<select class="kt-input" required name="client_id"><option value="">انتخاب کنید</option>@foreach($clients as $client)<option value="{{ $client->id }}">{{ $client->client_code }} — {{ $client->user?->display_name }}</option>@endforeach</select></label><label>اسلات آزاد<select class="kt-input" required name="slot_id" data-calendar-slots><option value="">زمان تقویم را انتخاب کنید</option></select></label><label>توضیح داخلی<textarea class="kt-input" name="notes" rows="3" maxlength="2000"></textarea></label><div class="secretary-modal-actions"><button type="button" class="ensha-secondary-btn" data-calendar-close>انصراف</button><button class="ensha-primary-btn" type="submit">ثبت نوبت</button></div><div class="secretary-modal-error" data-calendar-error></div></form></div>
@endif
@endsection
@push('scripts')<script src="{{ asset('js/secretary-calendar.js').'?v=0.16.0' }}"></script>@endpush
