@extends('layouts.app',['title'=>'برنامه هفتگی مشاور'])
@push('head')<link rel="stylesheet" href="{{ asset('css/stage06.css') }}">@endpush
@section('content')
<div class="ensha-page-heading"><h2>برنامه هفتگی مشاور</h2><div><a href="{{ route('counselor.week',['week'=>$week-1]) }}">هفته قبل</a> · <a href="{{ route('counselor.week',['week'=>0]) }}">این هفته</a> · <a href="{{ route('counselor.week',['week'=>$week+1]) }}">هفته بعد</a></div></div>
<form method="get" class="ensha-card stage06-card"><input type="hidden" name="week" value="{{ $week }}"><input name="topic_id" type="number" placeholder="شناسه موضوع" value="{{ request('topic_id') }}"><select name="status"><option value="">همه وضعیت‌ها</option>@foreach(\App\Models\Appointment::STATUSES as $status)<option @selected(request('status')===$status)>{{ $status }}</option>@endforeach</select><select name="mode"><option value="">همه شیوه‌ها</option><option value="in_person">حضوری</option><option value="video">آنلاین</option><option value="phone">تلفنی</option></select><button>فیلتر</button></form>
@for($i=0;$i<7;$i++)@php($date=$start->copy()->addDays($i)->toDateString())<section class="ensha-card stage06-card"><h3>{{ $date }}</h3>@forelse($appointments->get($date,collect()) as $a)<p><a href="{{ route('appointments.show',$a) }}">{{ $a->starts_at->format('H:i') }} — {{ $a->client?->user?->display_name }} · {{ $a->topic_name_snapshot ?: $a->topic?->name }} · {{ $a->status_snapshot ?: $a->status }}</a></p>@empty<p>نوبتی نیست.</p>@endforelse</section>@endfor
@if(auth()->user()->assignedRole?->slug==='counselor')<section class="ensha-card stage06-card"><h3>درخواست مرخصی</h3><form method="post" action="{{ route('counselor.leave') }}">@csrf<input name="branch_id" type="number" placeholder="شناسه شعبه (اختیاری)"><input name="starts_at" type="datetime-local" required><input name="ends_at" type="datetime-local" required><textarea name="reason" placeholder="علت" required></textarea><button>ارسال درخواست</button></form>@foreach($leaves as $leave)<p>{{ $leave->starts_at }} تا {{ $leave->ends_at }}: {{ $leave->status }}</p>@endforeach</section>@endif
@if(auth()->user()->hasPermission('leave_requests.manage'))<section class="ensha-card stage06-card"><h3>درخواست‌های در انتظار</h3>@foreach($pending as $leave)<div>{{ $leave->name }} · {{ $leave->starts_at }} تا {{ $leave->ends_at }} · {{ $leave->reason }}<form method="post" action="{{ route('counselor.leave.review',$leave->id) }}">@csrf<button name="decision" value="approved">تأیید</button><button name="decision" value="rejected">رد</button><input name="review_note" placeholder="یادداشت بررسی"></form></div>@endforeach</section>@endif
@endsection
