@extends('layouts.app', ['title'=>'جزئیات نوبت'])
@push('head')<link rel="stylesheet" href="{{ asset('css/stage09-finance.css').'?v=0.21.0' }}">@endpush
@section('content')
@include('appointments.partials.nav')
<div class="ensha-page-heading"><div><span class="ensha-eyebrow" dir="ltr">{{ $appointment->public_id ?: $appointment->appointment_number }}</span><h2>{{ $appointment->client?->user?->display_name }}</h2><p>{{ $appointment->topic_name_snapshot ?: $appointment->topic?->name }} با {{ $appointment->counselor?->display_name }}</p></div></div>
<section class="ensha-card" style="padding:22px"><div class="grid gap-4 md:grid-cols-3"><div><strong>شروع</strong><p>{{ $appointment->starts_at->format('Y-m-d H:i') }}</p></div><div><strong>پایان</strong><p>{{ $appointment->ends_at->format('Y-m-d H:i') }}</p></div><div><strong>وضعیت</strong><p>{{ $appointment->status_snapshot ?: $appointment->status }}</p></div><div><strong>شیوه</strong><p>{{ ['in_person'=>'حضوری','phone'=>'تلفنی','video'=>'ویدیویی'][$appointment->mode] ?? $appointment->mode }}</p></div><div><strong>اتاق</strong><p>{{ $appointment->slot?->room?->name ?: '—' }}</p></div><div><strong>قیمت پایه / نهایی</strong><p>{{ number_format($appointment->base_price) }} / {{ number_format($appointment->final_price) }} ریال</p></div><div><strong>پرداخت / مانده</strong><p>{{ number_format($appointment->paid_amount) }} / {{ number_format($appointment->balance_amount) }} ریال</p></div><div><strong>پرونده</strong><p>@if($appointment->client?->profile_state==='minimal')<a href="{{ route('stage06.clients.edit',$appointment->client) }}">⚠ ناقص؛ تکمیل کنید</a>@else کامل @endif</p></div></div></section>
@if(auth()->user()->hasPermission('session_reports.view'))<section class="ensha-card mt-4" style="padding:22px"><div class="flex items-center justify-between gap-3"><div><h3 class="text-lg font-semibold">گزارش جلسه</h3><p class="text-muted-foreground">ثبت گزارش متنی، فرم سریع و مشاهده سوابق این نوبت.</p></div><a class="ensha-primary-btn" href="{{ route('counselor.reports.show',$appointment) }}">بازکردن گزارش جلسه</a></div></section>@endif
@if(auth()->user()->hasPermission('payments.view'))@include('appointments.partials.payments')@endif
@if(auth()->user()->hasPermission('appointments.status'))<section class="ensha-card" style="padding:22px"><h3>تغییر وضعیت</h3><form method="POST" action="{{ route('appointments.transition',$appointment) }}" class="ensha-form-grid">@csrf @method('PATCH')<select name="status" required>@foreach($statuses as $status)@if($appointment->canTransitionTo($status->slug))<option value="{{ $status->slug }}">{{ $status->name }}</option>@endif @endforeach @foreach(\App\Models\Appointment::TRANSITIONS[$appointment->status] ?? [] as $slug)@if(!$statuses->contains('slug',$slug))<option value="{{ $slug }}">{{ $slug }}</option>@endif @endforeach</select><input name="reason" placeholder="دلیل / توضیح"><button class="ensha-primary-btn">ثبت وضعیت</button></form></section>@endif
<section class="ensha-card" style="padding:22px"><h3>تاریخچه وضعیت</h3><table class="ensha-table"><thead><tr><th>زمان</th><th>از</th><th>به</th><th>عامل</th><th>دلیل</th></tr></thead><tbody>@foreach($appointment->histories->sortByDesc('changed_at') as $history)<tr><td>{{ $history->changed_at?->format('Y-m-d H:i') }}</td><td>{{ $history->from_status ?: 'ایجاد' }}</td><td>{{ $history->to_status }}</td><td>{{ $history->actor?->display_name ?: 'سیستم' }}</td><td>{{ $history->reason ?: '—' }}</td></tr>@endforeach</tbody></table></section>
@endsection
@push('scripts')<script src="{{ asset('js/stage07-clinical.js').'?v=0.19.0' }}"></script>@endpush
