@extends('layouts.app',['title'=>'تنظیمات نوبت‌دهی '.$centre->name])
@push('head')<link rel="stylesheet" href="{{ asset('css/appointments-settings.css').'?v=0.18.8' }}">@endpush
@section('content')
<div class="ensha-page-heading appointments-settings-heading"><div><span class="ensha-eyebrow">مدیریت مرکز</span><h2>تنظیمات نوبت‌دهی</h2><p>{{ $centre->name }} · تنظیمات این صفحه فقط برای همین مرکز اعمال می‌شود.</p></div><a class="ensha-secondary-btn" href="{{ route('appointments.calendar') }}"><i class="ki-filled ki-calendar-8"></i> مشاهده تقویم</a></div>

<div class="appointment-tabs" role="tablist" aria-label="بخش‌های تنظیمات نوبت‌دهی">
@foreach(['policy'=>['قوانین ثبت نوبت','ki-setting-2'],'discounts'=>['تخفیف‌ها','ki-discount'],'mappings'=>['تخصص و تعرفه','ki-profile-user'],'statuses'=>['وضعیت‌های نوبت','ki-check-circle'],'records'=>['تنظیمات پرونده','ki-folder'],'permissions'=>['دسترسی فیلدها','ki-shield-tick']] as $key=>$tab)<button type="button" class="appointment-tab {{ $loop->first?'active':'' }}" data-tab="{{ $key }}" role="tab" aria-selected="{{ $loop->first?'true':'false' }}"><i class="ki-filled {{ $tab[1] }}"></i>{{ $tab[0] }}</button>@endforeach
</div>

<section class="appointment-pane active" data-pane="policy">
<div class="settings-card-head"><div><h3>قوانین ثبت نوبت این مرکز</h3><p>هر قانون مستقل است و فقط برای {{ $centre->name }} اعمال می‌شود.</p></div></div>
<form method="post" action="{{ route('centres.appointments-settings.booking-policy',$centre) }}" class="policy-form">@csrf
<div class="policy-row"><div class="policy-copy"><span class="policy-icon blue"><i class="ki-filled ki-home-2"></i></span><div><strong>بررسی اتاق برای نوبت حضوری</strong><small>در صورت فعال بودن، وجود اتاق آزاد قبل از ثبت نوبت کنترل می‌شود.</small></div></div><select class="kt-select" name="check_rooms"><option value="0" @selected(! $bookingPolicy->check_rooms)>غیرفعال</option><option value="1" @selected($bookingPolicy->check_rooms)>فعال</option></select></div>
<div class="policy-row"><div class="policy-copy"><span class="policy-icon amber"><i class="ki-filled ki-time"></i></span><div><strong>ثبت نوبت در زمان گذشته</strong><small>برای ورود دستی سوابق توسط منشی؛ تداخل مشاور و مراجع همچنان بررسی می‌شود.</small></div></div><select class="kt-select" name="allow_past_bookings"><option value="0" @selected(! $bookingPolicy->allow_past_bookings)>غیرفعال</option><option value="1" @selected($bookingPolicy->allow_past_bookings)>فعال</option></select></div>
<div class="settings-actions"><button class="kt-btn kt-btn-primary" type="submit"><i class="ki-filled ki-check"></i> ذخیره قوانین</button></div></form>
</section>

<section class="appointment-pane" data-pane="discounts" hidden>
<div class="settings-card-head"><div><h3>تخفیف‌ها</h3><p>تخفیف‌ها و بازه اعتبار مرکز را مدیریت کنید.</p></div><span class="count-badge">{{ $discounts->count() }} مورد</span></div>
<form method="post" action="{{ route('centres.appointments-settings.discounts.store',$centre) }}" class="settings-form-grid">@csrf
<label>نام تخفیف<input class="kt-input" name="name" required></label><label>نوع<select class="kt-select" name="type"><option value="percent">درصدی</option><option value="fixed">مبلغ ثابت</option></select></label><label>مقدار<input class="kt-input" name="value" type="number" min="1" required></label><label>حداقل مبلغ<input class="kt-input" name="minimum_amount" type="number" min="0"></label><label>سقف تخفیف<input class="kt-input" name="maximum_discount" type="number" min="0"></label><label>شروع اعتبار<input class="kt-input" name="starts_at" type="datetime-local"></label><label>پایان اعتبار<input class="kt-input" name="ends_at" type="datetime-local"></label><label class="check-line"><input type="checkbox" name="is_active" value="1" checked> فعال باشد</label><div class="form-submit"><button class="kt-btn kt-btn-primary">ثبت تخفیف</button></div></form>
<div class="ensha-table-wrap settings-table"><table class="ensha-table"><thead><tr><th>عنوان</th><th>نوع و مقدار</th><th>حداقل خرید</th><th>سقف</th><th>بازه اعتبار</th><th>وضعیت</th></tr></thead><tbody>
@forelse($discounts as $d)<tr><td><strong>{{ $d->name }}</strong></td><td>{{ $d->type==='percent' ? $d->value.'٪' : number_format($d->value).' ریال' }}</td><td>{{ $d->minimum_amount ? number_format($d->minimum_amount).' ریال':'—' }}</td><td>{{ $d->maximum_discount ? number_format($d->maximum_discount).' ریال':'—' }}</td><td>{{ $d->starts_at ?: 'بدون محدودیت' }}<br><small>{{ $d->ends_at ?: '' }}</small></td><td><span class="ensha-status {{ $d->is_active?'success':'warning' }}">{{ $d->is_active?'فعال':'غیرفعال' }}</span></td></tr>@empty<tr><td colspan="6" class="ensha-table-empty">تخفیفی ثبت نشده است.</td></tr>@endforelse
</tbody></table></div></section>

<section class="appointment-pane" data-pane="mappings" hidden>
<div class="settings-card-head"><div><h3>تخصص مشاور و تعرفه اختصاصی</h3><p>برای نوبت‌دهی، موضوع باید در این جدول به مشاور تخصیص داده شده و فعال باشد.</p></div><span class="count-badge">{{ $mappings->count() }} تخصیص</span></div>
<form method="post" action="{{ route('centres.appointments-settings.mappings.store',$centre) }}" class="settings-form-grid">@csrf
<label>مشاور<select class="kt-select" name="counselor_id" required>@foreach($counselors as $c)<option value="{{ $c->id }}">{{ $c->name }}</option>@endforeach</select></label><label>موضوع<select class="kt-select" name="topic_id" required>@foreach($topics as $t)<option value="{{ $t->id }}">{{ $t->name }}</option>@endforeach</select></label><label>تعرفه اختصاصی<input class="kt-input" name="price_override" type="number" min="0" placeholder="ریال"></label><label>مدت اختصاصی<input class="kt-input" name="duration_override" type="number" min="1" max="1440" placeholder="دقیقه"></label><label>معتبر از<input class="kt-input" name="valid_from" type="date"></label><label>معتبر تا<input class="kt-input" name="valid_until" type="date"></label><label class="check-line"><input type="checkbox" name="is_active" value="1" checked> تخصیص فعال</label><div class="form-submit"><button class="kt-btn kt-btn-primary">ثبت یا به‌روزرسانی تخصیص</button></div></form>
<div class="ensha-table-wrap settings-table"><table class="ensha-table"><thead><tr><th>مشاور</th><th>موضوع</th><th>تعرفه</th><th>مدت</th><th>بازه اعتبار</th><th>وضعیت</th></tr></thead><tbody>
@forelse($mappings as $m)<tr><td><strong>{{ $m->counselor_name }}</strong></td><td>{{ $m->topic_name }}</td><td>{{ $m->price_override!==null ? number_format($m->price_override).' ریال':'تعرفه عمومی' }}</td><td>{{ $m->duration_override ? $m->duration_override.' دقیقه':'پیش‌فرض' }}</td><td>{{ $m->valid_from ?: 'همیشگی' }}{{ $m->valid_until ? ' تا '.$m->valid_until:'' }}</td><td><span class="ensha-status {{ $m->is_active?'success':'warning' }}">{{ $m->is_active?'فعال':'غیرفعال' }}</span></td></tr>@empty<tr><td colspan="6" class="ensha-table-empty">هنوز موضوعی به مشاوران تخصیص داده نشده است.</td></tr>@endforelse
</tbody></table></div></section>

<section class="appointment-pane" data-pane="statuses" hidden>
<div class="settings-card-head"><div><h3>وضعیت‌های نوبت</h3><p>رنگ و رفتار وضعیت‌های گردش کار نوبت را تعیین کنید.</p></div></div>
<form method="post" action="{{ route('centres.appointments-settings.statuses.store',$centre) }}" class="settings-form-grid">@csrf<label>عنوان<input class="kt-input" name="name" required></label><label>کلید انگلیسی<input class="kt-input" name="slug" required></label><label>ترتیب<input class="kt-input" name="sort_order" type="number" min="0" value="99"></label><label>رنگ نشانگر<input class="kt-input color-input" name="indicator_color" type="color" value="#16a34a"></label><label>رنگ متن<input class="kt-input color-input" name="text_color" type="color" value="#111827"></label><label class="check-line"><input type="checkbox" name="is_final" value="1"> نهایی</label><label class="check-line"><input type="checkbox" name="blocks_slot" value="1" checked> اشغال زمان</label><div class="form-submit"><button class="kt-btn kt-btn-primary">ثبت وضعیت</button></div></form>
<div class="ensha-table-wrap settings-table"><table class="ensha-table"><thead><tr><th>عنوان</th><th>کلید</th><th>ترتیب</th><th>نهایی</th><th>اشغال زمان</th></tr></thead><tbody>@foreach($statuses as $s)<tr><td><span class="status-preview" style="background:{{ $s->indicator_color }};color:{{ $s->text_color }}">{{ $s->name }}</span></td><td>{{ $s->slug }}</td><td>{{ $s->sort_order }}</td><td>{{ $s->is_final?'بله':'خیر' }}</td><td>{{ $s->blocks_slot?'بله':'خیر' }}</td></tr>@endforeach</tbody></table></div></section>

<section class="appointment-pane" data-pane="records" hidden>
<div class="settings-card-head"><div><h3>تنظیمات پرونده</h3><p>زمان ایجاد پرونده و نقش‌های مجاز برای تکمیل آن.</p></div></div>
@php($selectedRoles=json_decode($record?->completer_roles ?? '[]',true) ?: ['manager','secretary','counselor','client'])
<form method="post" action="{{ route('centres.appointments-settings.records.settings',$centre) }}" class="record-form">@csrf<div class="settings-form-grid"><label>زمان ایجاد پیش‌نویس<select class="kt-select" name="draft_on"><option value="booking" @selected(($record?->draft_on??'booking')==='booking')>هنگام رزرو</option><option value="manual" @selected($record?->draft_on==='manual')>دستی</option></select></label><label>الزام تکمیل<select class="kt-select" name="complete_required_on"><option value="never" @selected(($record?->complete_required_on??'never')==='never')>بدون الزام</option><option value="arrival" @selected($record?->complete_required_on==='arrival')>هنگام مراجعه</option><option value="session" @selected($record?->complete_required_on==='session')>پیش از جلسه</option></select></label></div><h4>نقش‌های مجاز برای تکمیل پرونده</h4><div class="role-checks">@foreach(['manager'=>'مدیر','secretary'=>'منشی','counselor'=>'مشاور','client'=>'مراجع'] as $role=>$title)<label><input type="checkbox" name="completer_roles[]" value="{{ $role }}" @checked(in_array($role,$selectedRoles,true))>{{ $title }}</label>@endforeach</div><div class="settings-actions"><button class="kt-btn kt-btn-primary">ذخیره تنظیمات پرونده</button></div></form></section>

<section class="appointment-pane" data-pane="permissions" hidden>
<div class="settings-card-head"><div><h3>دسترسی فیلدهای پویای مراجع</h3><p>سطح مشاهده و ویرایش هر فیلد را برای نقش‌ها تعیین کنید.</p></div></div>
<form method="post" action="{{ route('centres.appointments-settings.records.permissions',$centre) }}" class="settings-form-grid">@csrf<label>فیلد<select class="kt-select" name="field_id">@foreach($fields as $f)<option value="{{ $f->id }}">{{ $f->label }}</option>@endforeach</select></label><label>نقش<select class="kt-select" name="role">@foreach(['manager'=>'مدیر','secretary'=>'منشی','counselor'=>'مشاور','client'=>'مراجع'] as $role=>$title)<option value="{{ $role }}">{{ $title }}</option>@endforeach</select></label><label class="check-line"><input type="checkbox" name="can_view" value="1"> مشاهده</label><label class="check-line"><input type="checkbox" name="can_edit" value="1"> ویرایش</label><div class="form-submit"><button class="kt-btn kt-btn-primary">ذخیره دسترسی</button></div></form></section>
@endsection
@push('scripts')<script src="{{ asset('js/appointments-settings.js').'?v=0.18.8' }}"></script>@endpush
