@extends('layouts.app',['title'=>'تنظیمات Stage 06'])
@push('head')<link rel="stylesheet" href="{{ asset('css/stage06.css') }}">@endpush
@section('content')
<div class="ensha-page-heading"><h2>تنظیمات نوبت‌دهی و پرونده</h2></div>
<section class="ensha-card stage06-card"><h3>تخفیف‌ها</h3><form method="post" action="{{ route('stage06.discounts.store') }}">@csrf<input name="name" placeholder="نام" required><select name="type"><option value="percent">درصدی</option><option value="fixed">ثابت</option></select><input name="value" type="number" min="1" placeholder="مقدار" required><input name="minimum_amount" type="number" min="0" placeholder="حداقل مبلغ"><input name="maximum_discount" type="number" min="0" placeholder="سقف تخفیف"><input name="starts_at" type="datetime-local"><input name="ends_at" type="datetime-local"><label><input type="checkbox" name="is_active" value="1" checked>فعال</label><button>ثبت</button></form>
@foreach($discounts as $d)<p>{{ $d->name }} · {{ $d->type }} {{ $d->value }} · {{ $d->is_active?'فعال':'غیرفعال' }}</p>@endforeach</section>
<section class="ensha-card stage06-card"><h3>وضعیت‌های نوبت</h3><form method="post" action="{{ route('stage06.statuses.store') }}">@csrf<input name="name" placeholder="عنوان" required><input name="slug" placeholder="کلید انگلیسی" required><label>نشانگر <input name="indicator_color" type="color" value="#16a34a"></label><label>متن <input name="text_color" type="color" value="#111827"></label><label><input type="checkbox" name="is_final" value="1"> نهایی</label><label><input type="checkbox" name="blocks_slot" value="1" checked> اشغال زمان</label><button>ثبت</button></form>@foreach($statuses as $s)<p><span style="background:{{ $s->indicator_color }};color:{{ $s->text_color }}">{{ $s->name }}</span> · {{ $s->slug }}</p>@endforeach</section>
<section class="ensha-card stage06-card"><h3>تخصص مشاور و تعرفه اختصاصی</h3><form method="post" action="{{ route('stage06.mappings.store') }}">@csrf<select name="counselor_id" required>@foreach($counselors as $c)<option value="{{ $c->id }}">{{ $c->name }}</option>@endforeach</select><select name="topic_id" required>@foreach($topics as $t)<option value="{{ $t->id }}">{{ $t->name }}</option>@endforeach</select><input name="price_override" type="number" min="0" placeholder="قیمت اختصاصی"><input name="duration_override" type="number" min="1" placeholder="مدت اختصاصی"><input name="valid_from" type="date"><input name="valid_until" type="date"><label><input type="checkbox" name="is_active" value="1" checked>فعال</label><button>ثبت</button></form><p>{{ $mappings->count() }} تخصیص در این مرکز</p></section>
<section class="ensha-card stage06-card"><h3>تنظیمات پرونده</h3><form method="post" action="{{ route('stage06.records.settings') }}">@csrf<label>زمان ایجاد Draft<select name="draft_on"><option value="booking">هنگام رزرو</option><option value="manual">دستی</option></select></label><label>الزام تکمیل<select name="complete_required_on"><option value="never">بدون الزام</option><option value="arrival">هنگام مراجعه</option><option value="session">پیش از جلسه</option></select></label>@foreach(['manager'=>'مدیر','secretary'=>'منشی','counselor'=>'مشاور','client'=>'مراجع'] as $role=>$title)<label><input type="checkbox" name="completer_roles[]" value="{{ $role }}" checked>{{ $title }}</label>@endforeach<button>ثبت</button></form></section>
<section class="ensha-card stage06-card"><h3>دسترسی فیلدهای پویای مراجع</h3><form method="post" action="{{ route('stage06.records.permissions') }}">@csrf<select name="field_id">@foreach($fields as $f)<option value="{{ $f->id }}">{{ $f->label }}</option>@endforeach</select><select name="role">@foreach(['manager','secretary','counselor','client'] as $role)<option value="{{ $role }}">{{ $role }}</option>@endforeach</select><label><input type="checkbox" name="can_view" value="1">مشاهده</label><label><input type="checkbox" name="can_edit" value="1">ویرایش</label><button>ثبت</button></form></section>
@endsection
