<?php

use App\Http\Controllers\ActiveRoleController;
use App\Http\Controllers\AccountPasswordController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\CentreOperationsController;
use App\Http\Controllers\CentreBranchController;
use App\Http\Controllers\CentreController;
use App\Http\Controllers\CentreSettingsController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ClientMergeController;
use App\Http\Controllers\ClientRecordController;
use App\Http\Controllers\CaseClinicalController;
use App\Http\Controllers\CounsellingCaseController;
use App\Http\Controllers\PrivateFileController;
use App\Http\Controllers\StaffController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ImpersonationController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\ProfileFieldController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\SelfProfileController;
use App\Http\Controllers\UserAssignmentController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UserSessionController;
use App\Http\Controllers\AppointmentController;
use App\Http\Controllers\AppointmentSlotController;
use App\Http\Controllers\ServiceTariffController;
use App\Http\Controllers\ScheduleExceptionController;
use App\Http\Controllers\SecretaryCalendarController;
use App\Http\Controllers\DailyOperationsController;
use App\Http\Controllers\TelephoneConsultationController;
use App\Http\Controllers\Stage06ClientController;
use App\Http\Controllers\Stage06SettingsController;
use App\Http\Controllers\StaffAttendanceController;
use App\Http\Controllers\CounselorWorkspaceController;
use Illuminate\Support\Facades\Route;

Route::get('/login', [AuthController::class, 'showLogin'])->name('login');
Route::post('/login', [AuthController::class, 'login'])->middleware('throttle:login')->name('login.store');
Route::get('/register', [AuthController::class, 'showRegister'])->name('register');
Route::post('/register', [AuthController::class, 'register'])->middleware('throttle:registration')->name('register.store');

Route::middleware('auth')->group(function () {
    Route::post('/logout', [AuthController::class, 'logout'])->name('logout');
    Route::get('/account/password', [AccountPasswordController::class, 'edit'])->name('account.password.edit');
    Route::put('/account/password', [AccountPasswordController::class, 'update'])->name('account.password.update');
    Route::post('/impersonation/stop', [ImpersonationController::class, 'stop'])->name('impersonation.stop');

    Route::middleware('password.changed')->group(function () {
        Route::get('/', fn () => redirect()->route('dashboard'))->name('home');
        Route::get('/account/roles', [ActiveRoleController::class, 'index'])->name('account.roles');
        Route::post('/account/roles/{assignment}', [ActiveRoleController::class, 'select'])->name('account.roles.select');
        Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

        Route::get('/centres', [CentreController::class, 'index'])->name('centres.index');
        Route::get('/centres/create', [CentreController::class, 'create'])->name('centres.create');
        Route::post('/centres', [CentreController::class, 'store'])->name('centres.store');
        Route::get('/centres/{centre}', [CentreController::class, 'show'])->name('centres.show');
        Route::get('/centres/{centre}/edit', [CentreController::class, 'edit'])->name('centres.edit');
        Route::put('/centres/{centre}', [CentreController::class, 'update'])->name('centres.update');
        Route::get('/centres/{centre}/branches', [CentreBranchController::class, 'index'])->name('centres.branches.index');
        Route::post('/centres/{centre}/branches', [CentreBranchController::class, 'store'])->name('centres.branches.store');
        Route::put('/centres/{centre}/branches/{branch}', [CentreBranchController::class, 'update'])->name('centres.branches.update');
        Route::get('/centres/{centre}/settings', [CentreSettingsController::class, 'edit'])->name('centres.settings.edit');
        Route::put('/centres/{centre}/settings', [CentreSettingsController::class, 'update'])->name('centres.settings.update');
        Route::get('/centres/{centre}/operations', [CentreOperationsController::class,'index'])->name('centres.operations');
        Route::post('/centres/{centre}/counselors', [CentreOperationsController::class,'attachCounselor'])->name('centres.operations.counselor');
        Route::post('/centres/{centre}/categories', [CentreOperationsController::class,'category'])->name('centres.operations.category');
        Route::post('/centres/{centre}/topics', [CentreOperationsController::class,'topic'])->name('centres.operations.topic');
        Route::put('/centres/{centre}/topics/{topic}', [CentreOperationsController::class,'updateTopic'])->name('centres.operations.topic.update');
        Route::post('/centres/{centre}/topic-assignments', [CentreOperationsController::class,'assign'])->name('centres.operations.assign');
        Route::post('/centres/{centre}/shifts', [CentreOperationsController::class,'shift'])->name('centres.operations.shift');
        Route::delete('/centres/{centre}/shifts/{shift}', [CentreOperationsController::class,'removeShift'])->name('centres.operations.shift.delete');
        Route::post('/centres/{centre}/closures', [CentreOperationsController::class,'closure'])->name('centres.operations.closure');
        Route::post('/centres/{centre}/leaves', [CentreOperationsController::class,'leave'])->name('centres.operations.leave');
        Route::post('/centres/{centre}/rooms', [CentreOperationsController::class,'room'])->name('centres.operations.room');
        Route::put('/centres/{centre}/rooms/{room}', [CentreOperationsController::class,'updateRoom'])->name('centres.operations.room.update');
        Route::get('/staff', [StaffController::class, 'index'])->name('staff.index');
        Route::get('/staff/{user}/edit', [StaffController::class, 'edit'])->name('staff.edit');
        Route::put('/staff/{user}', [StaffController::class, 'update'])->name('staff.update');

        Route::get('/clients', [ClientController::class, 'index'])->name('clients.index');
        Route::get('/clients/create', [ClientController::class, 'create'])->name('clients.create');
        Route::post('/clients', [ClientController::class, 'store'])->name('clients.store');
        Route::get('/clients/{client}', [ClientController::class, 'show'])->name('clients.show');
        Route::get('/clients/{client}/edit', [ClientController::class, 'edit'])->name('clients.edit');
        Route::put('/clients/{client}', [ClientController::class, 'update'])->name('clients.update');
        Route::get('/client-duplicates', [ClientMergeController::class, 'index'])->name('clients.duplicates');
        Route::post('/client-merges', [ClientMergeController::class, 'store'])->middleware('throttle:sensitive')->name('clients.merge');
        Route::post('/clients/{client}/intakes', [ClientRecordController::class, 'storeIntake'])->name('clients.intakes.store');
        Route::post('/clients/{client}/guardians', [ClientRecordController::class, 'storeGuardian'])->name('clients.guardians.store');
        Route::delete('/clients/{client}/guardians/{guardian}', [ClientRecordController::class, 'destroyGuardian'])->name('clients.guardians.destroy');
        Route::post('/clients/{client}/emergency-contacts', [ClientRecordController::class, 'storeEmergencyContact'])->name('clients.emergency-contacts.store');
        Route::delete('/clients/{client}/emergency-contacts/{contact}', [ClientRecordController::class, 'destroyEmergencyContact'])->name('clients.emergency-contacts.destroy');
        Route::post('/clients/{client}/consents', [ClientRecordController::class, 'storeConsent'])->name('clients.consents.store');
        Route::patch('/clients/{client}/consents/{consent}/revoke', [ClientRecordController::class, 'revokeConsent'])->middleware('throttle:sensitive')->name('clients.consents.revoke');
        Route::post('/clients/{client}/private-files', [PrivateFileController::class, 'store'])->name('clients.private-files.store');
        Route::get('/private-files/{privateFile}/download', [PrivateFileController::class, 'download'])->name('private-files.download');
        Route::delete('/private-files/{privateFile}', [PrivateFileController::class, 'destroy'])->middleware('throttle:sensitive')->name('private-files.destroy');

        Route::get('/cases', [CounsellingCaseController::class, 'index'])->name('cases.index');
        Route::get('/cases/create', [CounsellingCaseController::class, 'create'])->name('cases.create');
        Route::post('/cases', [CounsellingCaseController::class, 'store'])->name('cases.store');
        Route::get('/cases/{case}', [CounsellingCaseController::class, 'show'])->name('cases.show');
        Route::get('/cases/{case}/edit', [CounsellingCaseController::class, 'edit'])->name('cases.edit');
        Route::put('/cases/{case}', [CounsellingCaseController::class, 'update'])->name('cases.update');
        Route::post('/cases/{case}/assignments', [CounsellingCaseController::class, 'assign'])->name('cases.assignments.store');
        Route::delete('/cases/{case}/assignments/{assignment}', [CounsellingCaseController::class, 'unassign'])->name('cases.assignments.destroy');
        Route::post('/cases/{case}/sessions', [CaseClinicalController::class, 'storeSession'])->name('cases.sessions.store');
        Route::post('/cases/{case}/sessions/{session}/notes', [CaseClinicalController::class, 'storeNote'])->name('cases.notes.store');
        Route::put('/cases/{case}/notes/{note}', [CaseClinicalController::class, 'updateNote'])->name('cases.notes.update');
        Route::patch('/cases/{case}/notes/{note}/finalize', [CaseClinicalController::class, 'finalizeNote'])->middleware('throttle:sensitive')->name('cases.notes.finalize');
        Route::post('/cases/{case}/notes/{note}/addenda', [CaseClinicalController::class, 'storeAddendum'])->name('cases.notes.addenda.store');

        Route::get('/appointments', [AppointmentController::class, 'index'])->name('appointments.index');
        Route::get('/operations', [DailyOperationsController::class, 'index'])->name('operations.index');
        Route::post('/operations/appointments/{appointment}/check-in', [DailyOperationsController::class, 'checkIn'])->middleware('throttle:sensitive')->name('operations.check-in');
        Route::post('/operations/appointments/{appointment}/start', [DailyOperationsController::class, 'startSession'])->middleware('throttle:sensitive')->name('operations.start');
        Route::post('/operations/appointments/{appointment}/end', [DailyOperationsController::class, 'endSession'])->middleware('throttle:sensitive')->name('operations.end');
        Route::post('/operations/appointments/{appointment}/no-show', [DailyOperationsController::class, 'noShow'])->middleware('throttle:sensitive')->name('operations.no-show');
        Route::post('/operations/appointments/{appointment}/cancel', [DailyOperationsController::class, 'cancel'])->middleware('throttle:sensitive')->name('operations.cancel');
        Route::post('/operations/appointments/{appointment}/reschedule', [DailyOperationsController::class, 'reschedule'])->middleware('throttle:sensitive')->name('operations.reschedule');
        Route::post('/operations/waitlist', [DailyOperationsController::class, 'storeWaitlist'])->middleware('throttle:sensitive')->name('operations.waitlist.store');
        Route::post('/operations/waitlist/{waitlist}/promote', [DailyOperationsController::class, 'promoteWaitlist'])->middleware('throttle:sensitive')->name('operations.waitlist.promote');
        Route::post('/operations/sms/reminders', [DailyOperationsController::class, 'sms'])->middleware('throttle:sensitive')->name('operations.sms.reminders');
        Route::get('/operations/report', [DailyOperationsController::class, 'report'])->name('operations.report');
        Route::get('/operations/telephone', [TelephoneConsultationController::class, 'index'])->name('operations.telephone');
        Route::post('/operations/telephone', [TelephoneConsultationController::class, 'store'])->middleware('throttle:sensitive')->name('operations.telephone.store');
        Route::get('/appointments/calendar', [SecretaryCalendarController::class, 'index'])->name('appointments.calendar');
        Route::prefix('/appointments/calendar/api')->name('appointments.calendar.api.')->group(function () {
            Route::get('/resources', [SecretaryCalendarController::class, 'resources'])->name('resources');
            Route::get('/events', [SecretaryCalendarController::class, 'events'])->name('events');
            Route::get('/available-slots', [SecretaryCalendarController::class, 'availableSlots'])->name('available-slots');
            Route::get('/quote', [SecretaryCalendarController::class, 'quote'])->name('quote');
            Route::post('/events', [SecretaryCalendarController::class, 'store'])->middleware('throttle:sensitive')->name('store');
            Route::patch('/events/{appointment}', [SecretaryCalendarController::class, 'updateEvent'])->middleware('throttle:sensitive')->name('update');
        });
        Route::get('/appointments/create', [AppointmentController::class, 'create'])->name('appointments.create');
        Route::post('/appointments', [AppointmentController::class, 'store'])->middleware('throttle:sensitive')->name('appointments.store');
        Route::get('/appointments/slots', [AppointmentSlotController::class, 'index'])->name('appointments.slots.index');
        Route::post('/appointments/slots/generate', [AppointmentSlotController::class, 'generate'])->middleware('throttle:sensitive')->name('appointments.slots.generate');
        Route::patch('/appointments/slots/{slot}/block', [AppointmentSlotController::class, 'block'])->middleware('throttle:sensitive')->name('appointments.slots.block');
        Route::get('/appointments/tariffs', [ServiceTariffController::class, 'index'])->name('appointments.tariffs.index');
        Route::post('/appointments/tariffs', [ServiceTariffController::class, 'store'])->middleware('throttle:sensitive')->name('appointments.tariffs.store');
        Route::post('/schedule-exceptions', [ScheduleExceptionController::class, 'store'])->name('schedule-exceptions.store');
        Route::delete('/schedule-exceptions/{exception}', [ScheduleExceptionController::class, 'destroy'])->name('schedule-exceptions.destroy');
        Route::get('/appointments/{appointment}', [AppointmentController::class, 'show'])->name('appointments.show');
        Route::patch('/appointments/{appointment}/status', [AppointmentController::class, 'transition'])->middleware('throttle:sensitive')->name('appointments.transition');
        Route::get('/stage06/clients/search', [Stage06ClientController::class,'search'])->middleware('throttle:sensitive')->name('stage06.clients.search');
        Route::post('/stage06/clients/quick', [Stage06ClientController::class,'quickCreate'])->middleware('throttle:sensitive')->name('stage06.clients.quick');
        Route::get('/stage06/clients/{client}/complete', [Stage06ClientController::class,'edit'])->name('stage06.clients.edit');
        Route::put('/stage06/clients/{client}/complete', [Stage06ClientController::class,'update'])->middleware('throttle:sensitive')->name('stage06.clients.update');
        Route::get('/stage06/settings', [Stage06SettingsController::class,'index'])->name('stage06.settings');
        Route::post('/stage06/booking-policy', [Stage06SettingsController::class,'bookingPolicy'])->middleware('throttle:sensitive')->name('stage06.booking-policy');
        Route::post('/stage06/discounts', [Stage06SettingsController::class,'discount'])->name('stage06.discounts.store');
        Route::post('/stage06/statuses', [Stage06SettingsController::class,'status'])->name('stage06.statuses.store');
        Route::post('/stage06/mappings', [Stage06SettingsController::class,'mapping'])->name('stage06.mappings.store');
        Route::post('/stage06/record-settings', [Stage06SettingsController::class,'record'])->name('stage06.records.settings');
        Route::post('/stage06/field-permissions', [Stage06SettingsController::class,'fieldPermission'])->name('stage06.records.permissions');
        Route::get('/attendance', [StaffAttendanceController::class,'index'])->name('attendance.index');
        Route::post('/attendance/start', [StaffAttendanceController::class,'start'])->middleware('throttle:sensitive')->name('attendance.start');
        Route::post('/attendance/end', [StaffAttendanceController::class,'end'])->middleware('throttle:sensitive')->name('attendance.end');
        Route::patch('/attendance/{session}', [StaffAttendanceController::class,'correct'])->middleware('throttle:sensitive')->name('attendance.correct');
        Route::post('/attendance/pay-rules', [StaffAttendanceController::class,'payRule'])->name('attendance.pay-rules');
        Route::get('/counselor/week', [CounselorWorkspaceController::class,'index'])->name('counselor.week');
        Route::post('/counselor/leave', [CounselorWorkspaceController::class,'requestLeave'])->name('counselor.leave');
        Route::post('/counselor/leave/{leave}/review', [CounselorWorkspaceController::class,'reviewLeave'])->name('counselor.leave.review');

        Route::get('/users', [UserController::class, 'index'])->name('users.index');
        Route::get('/users/export', [UserController::class, 'export'])->middleware('throttle:exports')->name('users.export');
        Route::get('/users/deleted', [UserController::class, 'trash'])->name('users.trash');
        Route::patch('/users/deleted/{user}/restore', [UserController::class, 'restore'])->middleware('throttle:sensitive')->name('users.restore');
        Route::get('/users/create', [UserController::class, 'create'])->name('users.create');
        Route::post('/users', [UserController::class, 'store'])->name('users.store');
        Route::get('/users/{user}/roles', [UserAssignmentController::class, 'edit'])->name('users.assignments.edit');
        Route::post('/users/{user}/roles', [UserAssignmentController::class, 'store'])->name('users.assignments.store');
        Route::delete('/users/{user}/roles/{assignment}', [UserAssignmentController::class, 'destroy'])->name('users.assignments.destroy');
        Route::get('/users/{user}', [UserController::class, 'show'])->name('users.show');
        Route::get('/users/{user}/edit', [UserController::class, 'edit'])->name('users.edit');
        Route::put('/users/{user}', [UserController::class, 'update'])->name('users.update');
        Route::patch('/users/{user}/status', [UserController::class, 'changeStatus'])->middleware('throttle:sensitive')->name('users.status');
        Route::patch('/users/{user}/password', [UserController::class, 'resetPassword'])->middleware('throttle:sensitive')->name('users.password');
        Route::patch('/users/{user}/sessions/revoke', [UserSessionController::class, 'revokeAll'])->middleware('throttle:sensitive')->name('users.sessions.revoke-all');
        Route::patch('/users/{user}/sessions/{userSession}/revoke', [UserSessionController::class, 'revoke'])->middleware('throttle:sensitive')->name('users.sessions.revoke');
        Route::post('/users/{user}/impersonate', [ImpersonationController::class, 'start'])->middleware('throttle:sensitive')->name('users.impersonate');
        Route::delete('/users/{user}', [UserController::class, 'destroy'])->name('users.destroy');

        Route::get('/roles', [RoleController::class, 'index'])->name('roles.index');
        Route::get('/roles/create', [RoleController::class, 'create'])->name('roles.create');
        Route::post('/roles', [RoleController::class, 'store'])->name('roles.store');
        Route::get('/roles/{role}/edit', [RoleController::class, 'edit'])->name('roles.edit');
        Route::put('/roles/{role}', [RoleController::class, 'update'])->name('roles.update');
        Route::delete('/roles/{role}', [RoleController::class, 'destroy'])->name('roles.destroy');
        Route::get('/permissions', [PermissionController::class, 'index'])->name('permissions.index');

        Route::middleware('permission:profile_fields.manage')->group(function () {
            Route::get('/profile-fields', [ProfileFieldController::class, 'index'])->name('profile-fields.index');
            Route::post('/profile-fields', [ProfileFieldController::class, 'store'])->name('profile-fields.store');
            Route::put('/profile-fields/save', [ProfileFieldController::class, 'saveDraft'])->name('profile-fields.save');
            Route::put('/profile-fields/save-all', [ProfileFieldController::class, 'saveAll'])->name('profile-fields.save-all');
            Route::put('/profile-fields/order', [ProfileFieldController::class, 'reorder'])->name('profile-fields.reorder');
            Route::put('/profile-fields/{profileField}', [ProfileFieldController::class, 'update'])->name('profile-fields.update');
            Route::post('/profile-fields/{profileField}/clone', [ProfileFieldController::class, 'cloneField'])->name('profile-fields.clone');
            Route::delete('/profile-fields/{profileField}', [ProfileFieldController::class, 'destroy'])->name('profile-fields.destroy');
        });

        Route::get('/module/profile', [SelfProfileController::class, 'show'])->name('profile.show');
        Route::put('/module/profile', [SelfProfileController::class, 'update'])->middleware('throttle:sensitive')->name('profile.update');

        Route::get('/centres/{centre}/topics', [CentreOperationsController::class,'topicsPage'])->name('centres.topics');
        Route::get('/centres/{centre}/work-hours', [CentreOperationsController::class,'workHours'])->name('centres.work-hours');
        Route::get('/centres/{centre}/holidays', [CentreOperationsController::class,'holidays'])->name('centres.holidays');
        Route::get('/centres/{centre}/leaves', [CentreOperationsController::class,'leavesPage'])->name('centres.leaves');
        Route::get('/centres/{centre}/rooms', [CentreOperationsController::class,'roomsPage'])->name('centres.rooms');
        Route::get('/module/work-hours', fn(\Illuminate\Http\Request $request) => redirect()->route('centres.work-hours', $request->user()->centre_id))->name('module.work-hours');
        Route::get('/module/fees', fn(\Illuminate\Http\Request $request) => redirect()->route('centres.topics', $request->user()->centre_id))->name('module.fees');
        Route::get('/module/appointments', fn() => redirect()->route('appointments.index'))->name('module.appointments');
        Route::get('/module/holidays', fn(\Illuminate\Http\Request $request) => redirect()->route('centres.holidays', $request->user()->centre_id))->name('module.holidays');
        Route::get('/module/leaves', fn(\Illuminate\Http\Request $request) => redirect()->route('centres.leaves', $request->user()->centre_id))->name('module.leaves');
        Route::get('/module/rooms', fn(\Illuminate\Http\Request $request) => redirect()->route('centres.rooms', $request->user()->centre_id))->name('module.rooms');
        Route::get('/module/{module}', [DashboardController::class, 'module'])->name('module');
    });
});
