@extends('layouts.app', ['title'=>$client->exists ? 'ویرایش پرونده مراجع' : 'ثبت پرونده مراجع'])
@section('content')
<div class="ensha-page-heading"><div><span class="ensha-eyebrow">پرونده مراجع</span><h2>{{ $client->exists ? 'ویرایش پرونده مراجع' : 'ثبت پرونده مراجع' }}</h2><p>اطلاعات پایه را ثبت کنید؛ پرونده‌های بالینی در Workهای بعدی اضافه می‌شوند.</p></div></div>
<section class="ensha-card"><form method="POST" action="{{ $client->exists ? route('clients.update',$client) : route('clients.store') }}" class="grid gap-4 md:grid-cols-2">@csrf @if($client->exists) @method('PUT') @endif
<label class="kt-form-label">حساب کاربری مراجع @if(!$client->exists)<select class="kt-input mt-1" name="user_id" required><option value="">انتخاب کنید</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->display_name }} — {{ $user->phone }}</option>@endforeach</select>@else<div class="kt-input mt-1">{{ $client->user?->display_name }} — {{ $client->user?->phone }}</div><input type="hidden" name="user_id" value="{{ $client->user_id }}">@endif</label>
<label class="kt-form-label">مرکز<select class="kt-input mt-1" name="centre_id" required>@foreach($centres as $centre)<option value="{{ $centre->id }}" @selected((int)old('centre_id',$client->centre_id)===$centre->id)>{{ $centre->name }}</option>@endforeach</select></label>
<label class="kt-form-label">وضعیت<select class="kt-input mt-1" name="status"><option value="active" @selected(old('status',$client->status ?: 'active')==='active')>فعال</option><option value="inactive" @selected(old('status',$client->status)==='inactive')>غیرفعال</option><option value="archived" @selected(old('status',$client->status)==='archived')>بایگانی‌شده</option></select></label>
<label class="kt-form-label">تاریخ تولد<input class="kt-input mt-1" type="date" name="date_of_birth" value="{{ old('date_of_birth',optional($client->date_of_birth)->format('Y-m-d')) }}"></label>
<label class="kt-form-label">جنسیت<input class="kt-input mt-1" name="gender" value="{{ old('gender',$client->gender) }}"></label><label class="kt-form-label">روش تماس ترجیحی<select class="kt-input mt-1" name="preferred_contact"><option value="">انتخاب کنید</option>@foreach(['phone'=>'تلفن','sms'=>'پیامک','email'=>'ایمیل','whatsapp'=>'واتساپ'] as $key=>$label)<option value="{{ $key }}" @selected(old('preferred_contact',$client->preferred_contact)===$key)>{{ $label }}</option>@endforeach</select></label>
<label class="kt-form-label">منبع معرفی<input class="kt-input mt-1" name="referral_source" value="{{ old('referral_source',$client->referral_source) }}"></label><label class="kt-form-label">ارائه‌دهنده هویت بیرونی<input class="kt-input mt-1" name="provider" value="{{ old('provider',$client->externalIdentities?->first()?->provider) }}" placeholder="wordpress"></label>
<label class="kt-form-label">شناسه بیرونی<input class="kt-input mt-1" name="external_id" value="{{ old('external_id',$client->externalIdentities?->first()?->external_id) }}"></label><label class="kt-form-label">نام کاربری بیرونی<input class="kt-input mt-1" name="external_username" value="{{ old('external_username',$client->externalIdentities?->first()?->external_username) }}"></label>
<label class="kt-form-label">ایمیل بیرونی<input class="kt-input mt-1" type="email" name="external_email" value="{{ old('external_email',$client->externalIdentities?->first()?->external_email) }}"></label><label class="kt-form-label md:col-span-2">یادداشت پایه<textarea class="kt-input mt-1" name="notes" rows="4">{{ old('notes',$client->notes) }}</textarea></label>
<div class="md:col-span-2 flex gap-2"><button class="ensha-primary-btn">ذخیره پرونده</button><a class="ensha-secondary-btn" href="{{ $client->exists ? route('clients.show',$client) : route('clients.index') }}">انصراف</a></div></form></section>
@endsection
