@extends('layouts.app', ['title'=>'پرونده '.$client->client_code])
@section('content')
@if($client->profile_state === 'minimal')<div class="ensha-card" role="alert">⚠ پرونده این مراجع ناقص است. <a href="{{ route('stage06.clients.edit',$client) }}">تکمیل پرونده</a></div>@endif
<div class="ensha-page-heading"><div><span class="ensha-eyebrow">پرونده جامع مراجع</span><h2>{{ $client->user?->display_name }}</h2><p dir="ltr">{{ $client->client_code }} · {{ $client->user?->phone }}</p></div><div class="flex gap-2">@if(auth()->user()->hasPermission('clients.duplicates'))<a class="ensha-secondary-btn" href="{{ route('clients.duplicates') }}">بررسی تکراری‌ها</a>@endif @if(auth()->user()->hasPermission('clients.manage') && !$client->merged_into_id)<a class="ensha-primary-btn" href="{{ route('clients.edit',$client) }}">ویرایش پرونده</a>@endif</div></div>
@if($client->merged_into_id)<div class="ensha-alert warning">این پرونده در <a href="{{ route('clients.show',$client->mergedInto) }}">{{ $client->mergedInto?->client_code }}</a> ادغام شده و فقط برای سابقه نگهداری می‌شود.</div>@endif

<div class="grid gap-4 lg:grid-cols-2">
<section class="ensha-card"><h3 class="text-lg font-semibold mb-4">اطلاعات پایه</h3><dl class="grid grid-cols-2 gap-4"><div><dt class="text-muted-foreground">مرکز</dt><dd>{{ $client->centre?->name ?: '—' }}</dd></div><div><dt class="text-muted-foreground">وضعیت</dt><dd>{{ ['active'=>'فعال','inactive'=>'غیرفعال','archived'=>'بایگانی‌شده'][$client->status] ?? $client->status }}</dd></div><div><dt class="text-muted-foreground">تاریخ تولد</dt><dd>{{ $client->date_of_birth?->format('Y-m-d') ?: '—' }}</dd></div><div><dt class="text-muted-foreground">تماس ترجیحی</dt><dd>{{ $client->preferred_contact ?: '—' }}</dd></div><div class="col-span-2"><dt class="text-muted-foreground">یادداشت</dt><dd class="whitespace-pre-line">{{ $client->notes ?: '—' }}</dd></div></dl></section>
<section class="ensha-card"><h3 class="text-lg font-semibold mb-4">هویت‌های بیرونی و پرونده‌ها</h3>@forelse($client->externalIdentities as $identity)<div class="border-b border-border py-2"><strong>{{ $identity->provider }}</strong><span class="block text-sm text-muted-foreground" dir="ltr">{{ $identity->external_id }}</span></div>@empty<p class="text-muted-foreground">هویت بیرونی ثبت نشده است.</p>@endforelse<div class="mt-4 flex flex-wrap gap-2">@foreach($client->cases as $case)<a class="ensha-secondary-btn" href="{{ route('cases.show',$case) }}">{{ $case->case_number }}</a>@endforeach</div></section>
</div>

@if(auth()->user()->hasPermission('intakes.view'))
<div class="grid gap-4 lg:grid-cols-2 mt-4">
<section class="ensha-card"><h3 class="text-lg font-semibold mb-4">پذیرش‌ها</h3>@forelse($client->intakes as $intake)<div class="border-b border-border py-3"><strong>{{ $intake->intake_number }}</strong><span class="block text-sm text-muted-foreground">{{ $intake->intake_date?->format('Y-m-d') ?: 'بدون تاریخ' }} · ریسک: {{ ['unknown'=>'نامشخص','low'=>'کم','medium'=>'متوسط','high'=>'بالا','critical'=>'بحرانی'][$intake->risk_level] ?? $intake->risk_level }} · {{ $intake->status }}</span>@if($intake->presenting_concern)<p class="mt-2 whitespace-pre-line">{{ $intake->presenting_concern }}</p>@endif</div>@empty<p class="text-muted-foreground">پذیرشی ثبت نشده است.</p>@endforelse
@if(auth()->user()->hasPermission('intakes.manage') && !$client->merged_into_id)<form method="POST" action="{{ route('clients.intakes.store',$client) }}" class="mt-4 grid gap-3">@csrf<div class="grid grid-cols-2 gap-3"><input class="kt-input" type="date" name="intake_date"><select class="kt-input" name="case_id"><option value="">بدون اتصال به پرونده</option>@foreach($client->cases as $case)<option value="{{ $case->id }}">{{ $case->case_number }}</option>@endforeach</select><select class="kt-input" name="status" required><option value="draft">پیش‌نویس</option><option value="complete">کامل</option></select><select class="kt-input" name="risk_level" required><option value="unknown">ریسک نامشخص</option><option value="low">کم</option><option value="medium">متوسط</option><option value="high">بالا</option><option value="critical">بحرانی</option></select></div><input class="kt-input" name="referral_source" placeholder="منبع ارجاع"><textarea class="kt-input" name="presenting_concern" rows="3" placeholder="مسئله و علت مراجعه"></textarea><textarea class="kt-input" name="medical_notes" rows="2" placeholder="ملاحظات پزشکی"></textarea><textarea class="kt-input" name="safeguarding_notes" rows="2" placeholder="ملاحظات حفاظتی"></textarea><button class="ensha-primary-btn">ثبت پذیرش</button></form>@endif</section>

<section class="ensha-card"><h3 class="text-lg font-semibold mb-4">ولی قانونی</h3>@forelse($client->guardians as $guardian)<div class="flex justify-between border-b border-border py-3"><div><strong>{{ $guardian->full_name }}</strong><span class="block text-sm text-muted-foreground">{{ $guardian->relationship }} · {{ $guardian->phone }} @if($guardian->is_primary) · اصلی @endif @if($guardian->has_legal_authority) · اختیار قانونی تأییدشده @endif</span></div>@if(auth()->user()->hasPermission('intakes.manage') && !$client->merged_into_id)<form method="POST" action="{{ route('clients.guardians.destroy',[$client,$guardian]) }}">@csrf @method('DELETE')<button class="ensha-secondary-btn">حذف</button></form>@endif</div>@empty<p class="text-muted-foreground">ولی قانونی ثبت نشده است.</p>@endforelse
@if(auth()->user()->hasPermission('intakes.manage') && !$client->merged_into_id)<form method="POST" action="{{ route('clients.guardians.store',$client) }}" class="mt-4 grid gap-3">@csrf<input class="kt-input" name="full_name" placeholder="نام کامل" required><div class="grid grid-cols-2 gap-3"><input class="kt-input" name="relationship" placeholder="نسبت" required><input class="kt-input" name="phone" placeholder="تلفن" required></div><input class="kt-input" name="national_id" placeholder="کد ملی"><label><input type="checkbox" name="is_primary" value="1"> ولی اصلی</label><label><input type="checkbox" name="has_legal_authority" value="1"> اختیار قانونی تأیید شد</label><textarea class="kt-input" name="verification_notes" placeholder="توضیحات احراز"></textarea><button class="ensha-primary-btn">ثبت ولی</button></form>@endif</section>
</div>

<div class="grid gap-4 lg:grid-cols-2 mt-4">
<section class="ensha-card"><h3 class="text-lg font-semibold mb-4">تماس‌های اضطراری</h3>@forelse($client->emergencyContacts as $contact)<div class="flex justify-between border-b border-border py-3"><div><strong>{{ $contact->full_name }}</strong><span class="block text-sm text-muted-foreground">{{ $contact->relationship }} · {{ $contact->phone }} · اولویت {{ $contact->priority }}</span></div>@if(auth()->user()->hasPermission('intakes.manage') && !$client->merged_into_id)<form method="POST" action="{{ route('clients.emergency-contacts.destroy',[$client,$contact]) }}">@csrf @method('DELETE')<button class="ensha-secondary-btn">حذف</button></form>@endif</div>@empty<p class="text-muted-foreground">تماس اضطراری ثبت نشده است.</p>@endforelse
@if(auth()->user()->hasPermission('intakes.manage') && !$client->merged_into_id)<form method="POST" action="{{ route('clients.emergency-contacts.store',$client) }}" class="mt-4 grid gap-3">@csrf<input class="kt-input" name="full_name" placeholder="نام کامل" required><div class="grid grid-cols-2 gap-3"><input class="kt-input" name="relationship" placeholder="نسبت" required><input class="kt-input" name="phone" placeholder="تلفن" required></div><input class="kt-input" type="number" min="1" max="10" name="priority" value="1" required><label><input type="checkbox" name="authorized_for_contact" value="1" checked> تماس در وضعیت اضطراری مجاز است</label><button class="ensha-primary-btn">ثبت تماس</button></form>@endif</section>

<section class="ensha-card"><h3 class="text-lg font-semibold mb-4">رضایت‌نامه‌ها</h3>@forelse($client->consents as $consent)<div class="border-b border-border py-3"><strong>{{ ['treatment'=>'درمان','data_processing'=>'پردازش داده','recording'=>'ضبط جلسه','guardian'=>'ولی قانونی','research'=>'پژوهش','other'=>'سایر'][$consent->consent_type] ?? $consent->consent_type }}</strong><span class="block text-sm {{ $consent->is_granted ? 'text-success' : 'text-danger' }}">{{ $consent->is_granted ? 'معتبر' : 'لغوشده' }} · نسخه {{ $consent->document_version }}</span>@if($consent->is_granted && auth()->user()->hasPermission('intakes.manage') && !$client->merged_into_id)<form method="POST" action="{{ route('clients.consents.revoke',[$client,$consent]) }}" class="flex gap-2 mt-2">@csrf @method('PATCH')<input class="kt-input" name="reason" placeholder="علت لغو" required><button class="ensha-secondary-btn">لغو</button></form>@endif</div>@empty<p class="text-muted-foreground">رضایت‌نامه ثبت نشده است.</p>@endforelse
@if(auth()->user()->hasPermission('intakes.manage') && !$client->merged_into_id)<form method="POST" action="{{ route('clients.consents.store',$client) }}" class="mt-4 grid gap-3">@csrf<select class="kt-input" name="consent_type" required><option value="treatment">درمان</option><option value="data_processing">پردازش داده</option><option value="recording">ضبط جلسه</option><option value="guardian">ولی قانونی</option><option value="research">پژوهش</option><option value="other">سایر</option></select><input class="kt-input" name="document_version" value="1.0" required><input class="kt-input" type="date" name="expires_at"><textarea class="kt-input" name="notes" placeholder="توضیحات"></textarea><button class="ensha-primary-btn">ثبت رضایت</button></form>@endif</section>
</div>
@endif

@if(auth()->user()->hasPermission('private_files.view'))
<section class="ensha-card mt-4"><h3 class="text-lg font-semibold mb-4">فایل‌های خصوصی</h3><div class="grid gap-3">@forelse($client->privateFiles as $file)<div class="flex items-center justify-between border-b border-border py-3"><div><strong>{{ $file->original_name }}</strong><span class="block text-sm text-muted-foreground">{{ $file->classification }} · {{ number_format($file->size_bytes/1024,1) }} KB · {{ $file->scan_status }}</span></div><div class="flex gap-2"><a class="ensha-secondary-btn" href="{{ route('private-files.download',$file) }}">دریافت</a>@if(auth()->user()->hasPermission('private_files.manage') && !$client->merged_into_id)<form method="POST" action="{{ route('private-files.destroy',$file) }}">@csrf @method('DELETE')<button class="ensha-secondary-btn">حذف</button></form>@endif</div></div>@empty<p class="text-muted-foreground">فایل خصوصی ثبت نشده است.</p>@endforelse</div>
@if(auth()->user()->hasPermission('private_files.manage') && !$client->merged_into_id)<form method="POST" enctype="multipart/form-data" action="{{ route('clients.private-files.store',$client) }}" class="mt-4 grid gap-3">@csrf<input class="kt-input" type="file" name="file" required><select class="kt-input" name="classification"><option value="confidential">محرمانه</option><option value="clinical">بالینی</option><option value="identity">هویتی</option><option value="consent">رضایت‌نامه</option></select><select class="kt-input" name="case_id"><option value="">بدون اتصال به پرونده</option>@foreach($client->cases as $case)<option value="{{ $case->id }}">{{ $case->case_number }}</option>@endforeach</select><input class="kt-input" name="description" placeholder="توضیح فایل"><button class="ensha-primary-btn">بارگذاری خصوصی</button></form>@endif</section>
@endif
@endsection
