@extends('layouts.app', ['title'=>'صندوق و دریافت‌ها'])
@push('head')<link rel="stylesheet" href="{{ asset('css/stage09-finance.css').'?v=0.21.0' }}">@endpush
@section('content')
<div class="ensha-page-heading"><div><span class="ensha-eyebrow">Stage 09</span><h2>صندوق و دفتر تراکنش‌ها</h2><p>دریافت مرحله‌ای، رسید شماره‌دار، برگشت وجه و تطبیق صندوق روزانه.</p></div></div>
<div class="finance-summary">
  <div><span>خالص دریافت امروز</span><strong>{{ number_format($summary['today_net']) }}</strong><small>ریال</small></div>
  <div><span>خالص نقد امروز</span><strong>{{ number_format($summary['today_cash']) }}</strong><small>ریال</small></div>
  <div><span>کل مانده نوبت‌ها</span><strong>{{ number_format($summary['outstanding']) }}</strong><small>ریال</small></div>
  <div><span>صندوق باز مرکز</span><strong>{{ number_format($summary['open_registers']) }}</strong><small>صندوق</small></div>
</div>
<section class="ensha-card finance-section">
  <div class="finance-section-head"><div><h3>صندوق من</h3><p>هر کاربر مالی یک صندوق روزانه مستقل دارد.</p></div>@if($openSession)<span class="finance-badge open">باز · {{ $openSession->session_number }}</span>@else<span class="finance-badge closed">بسته</span>@endif</div>
  @if(!$openSession)
    @if(auth()->user()->hasPermission('cash_register.manage'))<form method="POST" action="{{ route('finance.cash-register.open') }}" class="finance-form">@csrf<label>موجودی ابتدای صندوق (ریال)<input type="number" name="opening_cash_amount" min="0" value="0" required></label><label>یادداشت شروع<input name="opening_note" maxlength="1000"></label><button class="ensha-primary-btn">بازکردن صندوق</button></form>@endif
  @else
    <div class="finance-balance-grid"><div><span>موجودی اول دوره</span><strong>{{ number_format($openSession->opening_cash_amount) }}</strong></div><div><span>دریافت نقد</span><strong>{{ number_format($registerTotals['cash_payments']) }}</strong></div><div><span>برگشت نقد</span><strong>{{ number_format($registerTotals['cash_refunds']) }}</strong></div><div><span>وجه نقد مورد انتظار</span><strong>{{ number_format($openSession->opening_cash_amount + $registerTotals['cash_net']) }}</strong></div></div>
    @if(auth()->user()->hasPermission('cash_register.manage'))<form method="POST" action="{{ route('finance.cash-register.close',$openSession) }}" class="finance-form">@csrf<label>وجه نقد شمارش‌شده (ریال)<input type="number" name="counted_cash_amount" min="0" required></label><label>یادداشت بستن<input name="closing_note" maxlength="1000"></label><button class="ensha-secondary-btn">بستن و تطبیق صندوق</button></form>@endif
  @endif
</section>
<section class="ensha-card finance-section"><div class="finance-section-head"><div><h3>نوبت‌های دارای مانده</h3><p>برای ثبت دریافت، صفحه نوبت را باز کنید.</p></div></div><div class="overflow-x-auto"><table class="ensha-table"><thead><tr><th>نوبت</th><th>مراجع</th><th>مشاور</th><th>زمان</th><th>نهایی</th><th>پرداخت</th><th>مانده</th><th></th></tr></thead><tbody>@forelse($appointments as $appointment)<tr><td dir="ltr">{{ $appointment->appointment_number }}</td><td>{{ $appointment->client?->user?->display_name }}</td><td>{{ $appointment->counselor?->display_name }}</td><td data-jalali-datetime="{{ $appointment->starts_at?->toIso8601String() }}">{{ $appointment->starts_at?->format('Y-m-d H:i') }}</td><td>{{ number_format($appointment->final_price) }}</td><td>{{ number_format($appointment->paid_amount) }}</td><td class="finance-negative">{{ number_format($appointment->balance_amount) }}</td><td><a href="{{ route('appointments.show',$appointment) }}">دریافت وجه</a></td></tr>@empty<tr><td colspan="8">نوبت دارای مانده پیدا نشد.</td></tr>@endforelse</tbody></table></div></section>
<section class="ensha-card finance-section"><div class="finance-section-head"><div><h3>آخرین تراکنش‌ها</h3><p>تراکنش‌ها حذف یا ویرایش نمی‌شوند؛ اصلاح با سند جبرانی انجام می‌شود.</p></div></div><div class="overflow-x-auto"><table class="ensha-table"><thead><tr><th>زمان</th><th>سند</th><th>نوبت</th><th>نوع</th><th>روش</th><th>مبلغ</th><th>رسید</th></tr></thead><tbody>@forelse($transactions as $transaction)<tr><td data-jalali-datetime="{{ $transaction->occurred_at?->toIso8601String() }}">{{ $transaction->occurred_at?->format('Y-m-d H:i') }}</td><td dir="ltr">{{ $transaction->transaction_number }}</td><td><a href="{{ route('appointments.show',$transaction->appointment) }}">{{ $transaction->appointment?->appointment_number }}</a></td><td>{{ ['payment'=>'دریافت','refund'=>'برگشت','void'=>'ابطال'][$transaction->kind] ?? $transaction->kind }}</td><td>{{ ['cash'=>'نقدی','card'=>'کارت‌خوان','bank_transfer'=>'بانکی','online'=>'آنلاین','other'=>'سایر','legacy'=>'قدیمی'][$transaction->method] ?? $transaction->method }}</td><td class="{{ $transaction->signed_amount>=0?'finance-positive':'finance-negative' }}">{{ number_format($transaction->signed_amount) }}</td><td>@if($transaction->receipt)<a href="{{ route('finance.receipts.show',$transaction->receipt) }}">مشاهده</a>@else—@endif</td></tr>@empty<tr><td colspan="7">هنوز تراکنشی ثبت نشده است.</td></tr>@endforelse</tbody></table></div></section>
<section class="ensha-card finance-section"><div class="finance-section-head"><div><h3>آخرین صندوق‌ها</h3></div></div><div class="overflow-x-auto"><table class="ensha-table"><thead><tr><th>شماره</th><th>صندوقدار</th><th>شروع</th><th>پایان</th><th>مورد انتظار</th><th>شمارش‌شده</th><th>اختلاف</th><th>وضعیت</th></tr></thead><tbody>@foreach($recentSessions as $session)<tr><td dir="ltr">{{ $session->session_number }}</td><td>{{ $session->cashier?->display_name }}</td><td data-jalali-datetime="{{ $session->opened_at?->toIso8601String() }}">{{ $session->opened_at?->format('Y-m-d H:i') }}</td><td data-jalali-datetime="{{ $session->closed_at?->toIso8601String() }}">{{ $session->closed_at?->format('Y-m-d H:i') ?: '—' }}</td><td>{{ number_format($session->expected_cash_amount) }}</td><td>{{ is_null($session->counted_cash_amount)?'—':number_format($session->counted_cash_amount) }}</td><td class="{{ ($session->difference_amount??0)==0?'finance-positive':'finance-negative' }}">{{ is_null($session->difference_amount)?'—':number_format($session->difference_amount) }}</td><td>{{ $session->status==='open'?'باز':'بسته' }}</td></tr>@endforeach</tbody></table></div></section>
@endsection
@push('scripts')<script src="{{ asset('js/stage07-clinical.js').'?v=0.19.0' }}"></script>@endpush
