@extends('layouts.app',['title'=>'حضور کارکنان'])
@push('head')<link rel="stylesheet" href="{{ asset('css/stage06.css') }}">@endpush
@section('content')
<div class="ensha-page-heading"><h2>حضور و غیاب</h2></div>
<section class="ensha-card stage06-card"><h3>کار من</h3>
@if($open)<p>● در حال کار از {{ $open->started_at }}</p><form method="post" action="{{ route('attendance.end') }}">@csrf<button class="ensha-primary-btn">پایان کار</button></form>
@else<form method="post" action="{{ route('attendance.start') }}">@csrf<label>شعبه <select name="branch_id"><option value="">مرکز اصلی</option>@foreach($branches as $b)<option value="{{ $b->id }}">{{ $b->name }}</option>@endforeach</select></label><button class="ensha-primary-btn">آغاز کار</button></form>@endif
<p>امروز: {{ intdiv($today,60) }}:{{ sprintf('%02d',$today%60) }} · هفته: {{ intdiv($week,60) }}:{{ sprintf('%02d',$week%60) }} · ماه: {{ intdiv($month,60) }}:{{ sprintf('%02d',$month%60) }}</p></section>
@if($isManager)<section class="ensha-card stage06-card"><h3>گزارش ساعات کارکنان</h3><form method="get"><select name="staff_id"><option value="">همه کارکنان</option>@foreach($staffOptions as $staff)<option value="{{ $staff->id }}" @selected(request('staff_id')==$staff->id)>{{ $staff->name }}</option>@endforeach</select><select name="branch_id"><option value="">همه شعب</option>@foreach($branches as $b)<option value="{{ $b->id }}" @selected(request('branch_id')==$b->id)>{{ $b->name }}</option>@endforeach</select><input name="from" type="date" value="{{ request('from') }}"><input name="to" type="date" value="{{ request('to') }}"><button>فیلتر</button>@if(auth()->user()->hasPermission('payroll.view'))<a href="{{ route('reports.payroll.index',['from'=>request('from'),'to'=>request('to')]) }}">محاسبه حقوق</a>@endif</form>
<p>جمع: {{ $summary['total_minutes'] }} دقیقه · روز کاری: {{ $summary['days'] }} · میانگین: {{ $summary['average_minutes'] }} دقیقه · تأخیر: {{ $summary['late_minutes'] }} · خروج زودتر: {{ $summary['early_minutes'] }} · اضافه‌کار: {{ $summary['overtime_minutes'] }} · کسری: {{ $summary['shortfall_minutes'] }}</p>
<table class="stage06-table"><thead><tr><th>کارمند</th><th>آغاز</th><th>پایان</th><th>مدت</th><th>وضعیت</th><th>اصلاح</th></tr></thead><tbody>@foreach($report as $s)<tr><td>{{ $s->name }}</td><td>{{ $s->started_at }}</td><td>{{ $s->ended_at ?: 'باز' }}</td><td>{{ $s->duration_minutes ?? '—' }} دقیقه</td><td>{{ $s->status }}</td><td>@if(auth()->user()->hasPermission('attendance.manage') && $s->ended_at)<details><summary>اصلاح با دلیل</summary><form method="post" action="{{ route('attendance.correct',$s->id) }}">@csrf @method('PATCH')<input type="datetime-local" name="started_at" value="{{ str_replace(' ','T',substr($s->started_at,0,16)) }}" required><input type="datetime-local" name="ended_at" value="{{ str_replace(' ','T',substr($s->ended_at,0,16)) }}" required><input name="reason" placeholder="علت اصلاح" required><button>ثبت</button></form></details>@endif</td></tr>@endforeach</tbody></table>{{ $report->links() }}</section>@endif
@if(auth()->user()->hasPermission('attendance.manage'))<section class="ensha-card stage06-card"><h3>قاعده محاسبه دستمزد</h3><form method="post" action="{{ route('attendance.pay-rules') }}">@csrf<select name="staff_id" required><option value="">انتخاب کارمند</option>@foreach($staffOptions as $staff)<option value="{{ $staff->id }}">{{ $staff->name }}</option>@endforeach</select><select name="model"><option value="fixed">ثابت دوره</option><option value="hourly">ساعتی</option><option value="shift">مبلغ هر شیفت</option><option value="fixed_overtime">ثابت + اضافه‌کار</option><option value="combined">ثابت + ساعتی + اضافه‌کار</option></select><input name="base_amount" type="number" value="0" min="0" placeholder="مبلغ پایه/شیفت"><input name="hourly_amount" type="number" value="0" min="0" placeholder="نرخ ساعتی"><input name="overtime_amount" type="number" value="0" min="0" placeholder="نرخ اضافه‌کار"><input name="daily_target_minutes" type="number" min="1" placeholder="دقایق هدف روزانه"><input name="shift_starts_at" type="time"><input name="shift_ends_at" type="time"><input name="valid_from" type="date" required><input name="valid_until" type="date"><button>ثبت قاعده</button></form></section>@endif
@endsection
