@extends('layouts.app',['title'=>auth()->user()->assignedRole?->slug==='finance'?'داشبورد مالی':'داشبورد مدیر مرکز'])
@push('head')<link rel="stylesheet" href="{{ asset('css/stage11-reports.css').'?v=0.23.0' }}">@endpush
@section('content')
<div class="ensha-page-heading"><div><span class="ensha-eyebrow">Stage 11 · {{ $dashboard['month_label'] }}</span><h2>{{ auth()->user()->assignedRole?->slug==='finance'?'داشبورد مسئول مالی':'داشبورد مدیریتی مرکز' }}</h2><p>نمای زنده وصول، مانده، سهم مرکز و تعهدات تسویه در ماه شمسی جاری.</p></div><div class="report-actions"><a class="ensha-primary-btn" href="{{ route('reports.financial.index') }}">گزارش مالی کامل</a><a class="ensha-secondary-btn" href="{{ route('reports.payroll.index') }}">کارکرد و حقوق</a></div></div>
<div class="report-kpis"><div><span>وصول امروز</span><strong>{{ number_format($dashboard['today_net']) }}</strong><small>ریال</small></div><div><span>وصول ماه شمسی</span><strong>{{ number_format($dashboard['month_paid']) }}</strong><small>ریال</small></div><div><span>مانده مطالبات ماه</span><strong>{{ number_format($dashboard['month_balance']) }}</strong><small>ریال</small></div><div><span>سهم مرکز</span><strong>{{ number_format($dashboard['month_centre_share']) }}</strong><small>ریال</small></div><div><span>سهم مشاوران</span><strong>{{ number_format($dashboard['month_counselor_share']) }}</strong><small>ریال</small></div><div><span>تسویه آماده پرداخت</span><strong>{{ number_format($dashboard['approved_settlements']) }}</strong><small>ریال</small></div></div>
<div class="report-grid"><section class="ensha-card report-card"><div class="report-card-head"><div><h3>روند ماه‌های شمسی</h3><p>بر پایه مبلغ وصول‌شده نوبت‌ها</p></div></div><div class="report-bars">@php($max=max(1,$dashboard['months']->max('paid')??1)) @forelse($dashboard['months']->take(8)->reverse() as $month)<div><span>{{ $month->label }}</span><i><b style="width:{{ min(100,round($month->paid/$max*100)) }}%"></b></i><strong>{{ number_format($month->paid) }}</strong></div>@empty<p>داده‌ای وجود ندارد.</p>@endforelse</div></section>
<section class="ensha-card report-card"><div class="report-card-head"><div><h3>عملکرد مشاوران در ماه</h3><p>وصول و سهم قفل‌شده هر مشاور</p></div></div><div class="overflow-x-auto"><table class="ensha-table"><thead><tr><th>مشاور</th><th>جلسه</th><th>وصول</th><th>سهم مشاور</th></tr></thead><tbody>@forelse($dashboard['counselors'] as $row)<tr><td>{{ $row->counselor }}</td><td>{{ $row->appointments }}</td><td>{{ number_format($row->paid) }}</td><td>{{ number_format($row->counselor_share) }}</td></tr>@empty<tr><td colspan="4">داده‌ای وجود ندارد.</td></tr>@endforelse</tbody></table></div></section></div>
<div class="report-mini"><div><i class="ki-filled ki-check-circle"></i><span>جلسات تکمیل‌شده ماه</span><strong>{{ $dashboard['completed'] }}</strong></div><div><i class="ki-filled ki-wallet"></i><span>صندوق‌های باز</span><strong>{{ $dashboard['open_registers'] }}</strong></div><div><i class="ki-filled ki-calendar"></i><span>بازه ماه جاری</span><strong><span data-jalali-date="{{ $dashboard['start']->toDateString() }}">{{ $dashboard['start']->toDateString() }}</span> تا <span data-jalali-date="{{ $dashboard['end']->toDateString() }}">{{ $dashboard['end']->toDateString() }}</span></strong></div></div>
@endsection
@push('scripts')<script src="{{ asset('js/stage07-clinical.js').'?v=0.19.0' }}"></script>@endpush
