@extends('layouts.app',['title'=>'گزارش‌های مالی'])
@push('head')<link rel="stylesheet" href="{{ asset('css/stage11-reports.css').'?v=0.23.0' }}">@endpush
@section('content')
<div class="ensha-page-heading"><div><span class="ensha-eyebrow">Stage 11</span><h2>گزارش مالی مرکز</h2><p>مالی هر مشاوره، ماه‌های شمسی، مشاوران، بدهکاران، صندوق و تسویه در یک نمای فیلترپذیر.</p></div></div>
<section class="ensha-card report-filter"><form method="GET"><label>از تاریخ<input type="date" name="from" value="{{ $from }}"></label><label>تا تاریخ<input type="date" name="to" value="{{ $to }}"></label><label>مشاور<select name="counselor_id"><option value="">همه مشاوران</option>@foreach($counselorOptions as $option)<option value="{{ $option->id }}" @selected($counselorId===$option->id)>{{ $option->name }}</option>@endforeach</select></label><button class="ensha-primary-btn">اعمال فیلتر</button></form></section>
<div class="report-kpis"><div><span>تعداد مشاوره</span><strong>{{ number_format($summary['appointments']) }}</strong></div><div><span>مبلغ نهایی</span><strong>{{ number_format($summary['final']) }}</strong></div><div><span>وصول</span><strong>{{ number_format($summary['paid']) }}</strong></div><div><span>مانده</span><strong>{{ number_format($summary['balance']) }}</strong></div><div><span>سهم مرکز</span><strong>{{ number_format($summary['centre_share']) }}</strong></div><div><span>سهم مشاوران</span><strong>{{ number_format($summary['counselor_share']) }}</strong></div></div>
<nav class="report-tabs"><a href="#appointments">مالی مشاوره‌ها</a><a href="#months">ماه نوبت</a><a href="#collections">وصول ماه شمسی</a><a href="#counselors">مشاوران</a><a href="#debtors">بدهکاران</a><a href="#cash">صندوق</a><a href="#settlements">تسویه</a></nav>
@php($exportQuery=http_build_query(['from'=>$from,'to'=>$to,'counselor_id'=>$counselorId]))
<section id="appointments" class="ensha-card report-card"><div class="report-card-head"><div><h3>جدول مالی هر مشاوره</h3></div>@if(auth()->user()->hasPermission('finance.analytics.export'))<a href="{{ route('reports.financial.export','appointments').'?'.$exportQuery }}">خروجی XLSX</a>@endif</div><div class="overflow-x-auto"><table class="ensha-table"><thead><tr><th>نوبت</th><th>تاریخ</th><th>مراجع</th><th>مشاور</th><th>نهایی</th><th>وصول</th><th>مانده</th><th>سهم مرکز</th><th>سهم مشاور</th></tr></thead><tbody>@forelse($rows->take(500) as $row)<tr><td>{{ $row->appointment_number }}</td><td data-jalali-datetime="{{ $row->starts_at }}">{{ $row->starts_at }}</td><td>{{ $row->client_name }}</td><td>{{ $row->counselor_name }}</td><td>{{ number_format($row->final_price) }}</td><td>{{ number_format($row->paid_amount) }}</td><td class="report-negative">{{ number_format($row->balance_amount) }}</td><td>{{ number_format($row->centre_share_amount??0) }}</td><td>{{ number_format($row->counselor_share_amount??0) }}</td></tr>@empty<tr><td colspan="9">داده‌ای وجود ندارد.</td></tr>@endforelse</tbody></table></div></section>
<div class="report-grid"><section id="months" class="ensha-card report-card"><div class="report-card-head"><h3>ماه‌های شمسی</h3>@if(auth()->user()->hasPermission('finance.analytics.export'))<a href="{{ route('reports.financial.export','monthly').'?'.$exportQuery }}">XLSX</a>@endif</div><table class="ensha-table"><thead><tr><th>ماه</th><th>جلسه</th><th>وصول</th><th>مانده</th></tr></thead><tbody>@foreach($monthly as $row)<tr><td>{{ $row->label }}</td><td>{{ $row->appointments }}</td><td>{{ number_format($row->paid) }}</td><td>{{ number_format($row->balance) }}</td></tr>@endforeach</tbody></table></section>
<section id="counselors" class="ensha-card report-card"><div class="report-card-head"><h3>تفکیک مشاور</h3>@if(auth()->user()->hasPermission('finance.analytics.export'))<a href="{{ route('reports.financial.export','counselors').'?'.$exportQuery }}">XLSX</a>@endif</div><table class="ensha-table"><thead><tr><th>مشاور</th><th>جلسه</th><th>وصول</th><th>سهم</th></tr></thead><tbody>@foreach($counselors as $row)<tr><td>{{ $row->counselor }}</td><td>{{ $row->appointments }}</td><td>{{ number_format($row->paid) }}</td><td>{{ number_format($row->counselor_share) }}</td></tr>@endforeach</tbody></table></section></div>
<section id="collections" class="ensha-card report-card"><div class="report-card-head"><div><h3>وصول واقعی به تفکیک ماه شمسی</h3><p>بر پایه تاریخ تراکنش‌های قطعی دفتر مالی؛ برگشت و ابطال در خالص وصول اثر منفی دارند.</p></div>@if(auth()->user()->hasPermission('finance.analytics.export'))<a href="{{ route('reports.financial.export','collections').'?'.$exportQuery }}">XLSX</a>@endif</div><div class="overflow-x-auto"><table class="ensha-table"><thead><tr><th>ماه</th><th>تراکنش</th><th>نقد</th><th>کارت‌خوان</th><th>بانکی</th><th>آنلاین</th><th>سایر</th><th>خالص وصول</th></tr></thead><tbody>@forelse($collections as $row)<tr><td>{{ $row->label }}</td><td>{{ $row->transactions }}</td><td>{{ number_format($row->cash) }}</td><td>{{ number_format($row->card) }}</td><td>{{ number_format($row->bank_transfer) }}</td><td>{{ number_format($row->online) }}</td><td>{{ number_format($row->other) }}</td><td><b>{{ number_format($row->net) }}</b></td></tr>@empty<tr><td colspan="8">تراکنشی در بازه انتخابی وجود ندارد.</td></tr>@endforelse</tbody></table></div></section>
<section id="debtors" class="ensha-card report-card"><div class="report-card-head"><div><h3>بدهکاران</h3><p>نوبت‌های دارای مانده در بازه انتخابی</p></div>@if(auth()->user()->hasPermission('finance.analytics.export'))<a href="{{ route('reports.financial.export','debtors').'?'.$exportQuery }}">XLSX</a>@endif</div><div class="overflow-x-auto"><table class="ensha-table"><thead><tr><th>نوبت</th><th>مراجع</th><th>مشاور</th><th>نهایی</th><th>پرداخت</th><th>مانده</th></tr></thead><tbody>@forelse($debtors as $row)<tr><td>{{ $row->appointment_number }}</td><td>{{ $row->client_name }}</td><td>{{ $row->counselor_name }}</td><td>{{ number_format($row->final_price) }}</td><td>{{ number_format($row->paid_amount) }}</td><td class="report-negative">{{ number_format($row->balance_amount) }}</td></tr>@empty<tr><td colspan="6">بدهکاری وجود ندارد.</td></tr>@endforelse</tbody></table></div></section>
<section id="cash" class="ensha-card report-card"><div class="report-card-head"><h3>صندوق‌های روزانه</h3>@if(auth()->user()->hasPermission('finance.analytics.export'))<a href="{{ route('reports.financial.export','cash').'?'.$exportQuery }}">XLSX</a>@endif</div><div class="overflow-x-auto"><table class="ensha-table"><thead><tr><th>شماره</th><th>صندوقدار</th><th>شروع</th><th>دریافت نقد</th><th>برگشت</th><th>مورد انتظار</th><th>اختلاف</th></tr></thead><tbody>@foreach($cash as $row)<tr><td>{{ $row->session_number }}</td><td>{{ $row->cashier_name }}</td><td data-jalali-datetime="{{ $row->opened_at }}">{{ $row->opened_at }}</td><td>{{ number_format($row->cash_payments_amount) }}</td><td>{{ number_format($row->cash_refunds_amount) }}</td><td>{{ number_format($row->expected_cash_amount) }}</td><td>{{ number_format($row->difference_amount??0) }}</td></tr>@endforeach</tbody></table></div></section>
<section id="settlements" class="ensha-card report-card"><div class="report-card-head"><h3>تسویه مشاوران</h3>@if(auth()->user()->hasPermission('finance.analytics.export'))<a href="{{ route('reports.financial.export','settlements').'?'.$exportQuery }}">XLSX</a>@endif</div><div class="overflow-x-auto"><table class="ensha-table"><thead><tr><th>شماره</th><th>مشاور</th><th>وصول</th><th>قابل پرداخت</th><th>پرداخت‌شده</th><th>وضعیت</th></tr></thead><tbody>@foreach($settlements as $row)<tr><td>{{ $row->settlement_number }}</td><td>{{ $row->counselor_name }}</td><td>{{ number_format($row->gross_collected_amount) }}</td><td>{{ number_format($row->payable_amount) }}</td><td>{{ number_format($row->paid_amount) }}</td><td>{{ $row->status }}</td></tr>@endforeach</tbody></table></div></section>
@endsection
@push('scripts')<script src="{{ asset('js/stage07-clinical.js').'?v=0.19.0' }}"></script>@endpush
