@extends('layouts.app',['title'=>'کارکرد و حقوق'])
@push('head')<link rel="stylesheet" href="{{ asset('css/stage11-reports.css').'?v=0.23.0' }}">@endpush
@section('content')
<div class="ensha-page-heading"><div><span class="ensha-eyebrow">Stage 11</span><h2>کارکرد و حقوق کارکنان</h2><p>محاسبه از روی حضور بسته‌شده و قانون دستمزد معتبر در تاریخ هر شیفت.</p></div></div>
<section class="ensha-card report-filter"><form method="GET"><label>از تاریخ<input type="date" name="from" value="{{ $from }}" required></label><label>تا تاریخ<input type="date" name="to" value="{{ $to }}" required></label><button class="ensha-primary-btn">محاسبه زنده</button>@if(auth()->user()->hasPermission('payroll.export'))<a class="ensha-secondary-btn" href="{{ route('reports.payroll.export',['from'=>$from,'to'=>$to]) }}">خروجی XLSX</a>@endif</form></section>
<div class="report-kpis payroll"><div><span>کارکنان</span><strong>{{ $summary['staff'] }}</strong></div><div><span>کارکرد</span><strong>{{ number_format($summary['worked']) }}</strong><small>دقیقه</small></div><div><span>اضافه‌کار</span><strong>{{ number_format($summary['overtime']) }}</strong><small>دقیقه</small></div><div><span>کسری</span><strong>{{ number_format($summary['shortfall']) }}</strong><small>دقیقه</small></div><div><span>جمع قابل پرداخت</span><strong>{{ number_format($summary['payable']) }}</strong><small>ریال</small></div></div>
<section class="ensha-card report-card"><div class="report-card-head"><div><h3>محاسبه زنده دوره</h3><p>تا پیش از ساخت دوره، اصلاح حضور یا قانون دستمزد در این محاسبه اعمال می‌شود.</p></div></div><div class="overflow-x-auto"><table class="ensha-table"><thead><tr><th>کارمند</th><th>روز</th><th>کارکرد</th><th>تأخیر</th><th>خروج زودتر</th><th>اضافه‌کار</th><th>کسری</th><th>پایه/شیفت</th><th>ساعتی</th><th>اضافه‌کار</th><th>قابل پرداخت</th></tr></thead><tbody>@forelse($rows as $row)<tr><td>{{ $row->staff_name }}</td><td>{{ $row->worked_days }}</td><td>{{ $row->worked_minutes }}</td><td>{{ $row->late_minutes }}</td><td>{{ $row->early_minutes }}</td><td>{{ $row->overtime_minutes }}</td><td>{{ $row->shortfall_minutes }}</td><td>{{ number_format($row->base_pay_amount) }}</td><td>{{ number_format($row->hourly_pay_amount) }}</td><td>{{ number_format($row->overtime_pay_amount) }}</td><td><b>{{ number_format($row->payable_amount) }}</b></td></tr>@empty<tr><td colspan="11">حضور بسته‌شده‌ای در این دوره وجود ندارد.</td></tr>@endforelse</tbody></table></div></section>
@if(auth()->user()->hasPermission('payroll.manage'))<section class="ensha-card report-card"><div class="report-card-head"><div><h3>ساخت Snapshot دوره حقوق</h3><p>پس از ساخت، اقلام دوره ثابت می‌مانند و می‌توان دوره را قفل کرد.</p></div></div><form method="POST" action="{{ route('reports.payroll.runs.store') }}" class="report-create-run">@csrf<input type="hidden" name="from" value="{{ $from }}"><input type="hidden" name="to" value="{{ $to }}"><label>یادداشت دوره<input name="note" maxlength="2000" placeholder="مثلاً حقوق مهر ۱۴۰۵"></label><button class="ensha-primary-btn">ساخت دوره حقوق</button></form></section>@endif
<section class="ensha-card report-card"><div class="report-card-head"><h3>دوره‌های Snapshot شده</h3></div><div class="overflow-x-auto"><table class="ensha-table"><thead><tr><th>شماره</th><th>دوره</th><th>کارکنان</th><th>کارکرد</th><th>قابل پرداخت</th><th>وضعیت</th><th></th></tr></thead><tbody>@forelse($runs as $run)<tr><td dir="ltr">{{ $run->run_number }}</td><td><span data-jalali-date="{{ $run->period_start?->toDateString() }}">{{ $run->period_start?->toDateString() }}</span> تا <span data-jalali-date="{{ $run->period_end?->toDateString() }}">{{ $run->period_end?->toDateString() }}</span></td><td>{{ $run->staff_count }}</td><td>{{ number_format($run->total_worked_minutes) }}</td><td>{{ number_format($run->total_payable_amount) }}</td><td><span class="report-status {{ $run->status }}">{{ $run->status==='locked'?'قفل‌شده':'پیش‌نویس' }}</span></td><td><a href="{{ route('reports.payroll.runs.show',$run) }}">جزئیات</a></td></tr>@empty<tr><td colspan="7">دوره‌ای ساخته نشده است.</td></tr>@endforelse</tbody></table></div></section>
@endsection
@push('scripts')<script src="{{ asset('js/stage07-clinical.js').'?v=0.19.0' }}"></script>@endpush
