@extends('layouts.app',['title'=>'دوره حقوق'])
@push('head')<link rel="stylesheet" href="{{ asset('css/stage11-reports.css').'?v=0.23.0' }}">@endpush
@section('content')
<div class="ensha-page-heading"><div><span class="ensha-eyebrow" dir="ltr">{{ $run->run_number }}</span><h2>دوره حقوق</h2><p><span data-jalali-date="{{ $run->period_start?->toDateString() }}">{{ $run->period_start?->toDateString() }}</span> تا <span data-jalali-date="{{ $run->period_end?->toDateString() }}">{{ $run->period_end?->toDateString() }}</span></p></div><div class="report-actions"><a class="ensha-secondary-btn" href="{{ route('reports.payroll.index') }}">بازگشت</a>@if(auth()->user()->hasPermission('payroll.export'))<a class="ensha-primary-btn" href="{{ route('reports.payroll.runs.export',$run) }}">خروجی XLSX</a>@endif</div></div>
<div class="report-kpis payroll"><div><span>وضعیت</span><strong>{{ $run->status==='locked'?'قفل‌شده':'پیش‌نویس' }}</strong></div><div><span>کارکنان</span><strong>{{ $run->staff_count }}</strong></div><div><span>کارکرد</span><strong>{{ number_format($run->total_worked_minutes) }}</strong><small>دقیقه</small></div><div><span>جمع قابل پرداخت</span><strong>{{ number_format($run->total_payable_amount) }}</strong><small>ریال</small></div></div>
@if($run->status==='draft' && auth()->user()->hasPermission('payroll.manage'))<section class="ensha-card report-card"><form method="POST" action="{{ route('reports.payroll.runs.lock',$run) }}">@csrf<button class="ensha-primary-btn" onclick="return confirm('پس از قفل، اقلام این دوره ثابت می‌مانند. ادامه می‌دهید؟')">تأیید و قفل دوره</button></form></section>@endif
<section class="ensha-card report-card"><div class="report-card-head"><div><h3>اقلام Snapshot شده</h3><p>قانون و مبالغ هر کارمند در زمان ساخت دوره ذخیره شده‌اند.</p></div></div><div class="overflow-x-auto"><table class="ensha-table"><thead><tr><th>کارمند</th><th>روز</th><th>کارکرد</th><th>تأخیر</th><th>خروج زودتر</th><th>اضافه‌کار</th><th>کسری</th><th>پایه/شیفت</th><th>ساعتی</th><th>اضافه‌کار</th><th>قابل پرداخت</th></tr></thead><tbody>@foreach($run->items as $item)<tr><td>{{ $item->staff?->display_name }}</td><td>{{ $item->worked_days }}</td><td>{{ $item->worked_minutes }}</td><td>{{ $item->late_minutes }}</td><td>{{ $item->early_minutes }}</td><td>{{ $item->overtime_minutes }}</td><td>{{ $item->shortfall_minutes }}</td><td>{{ number_format($item->base_pay_amount) }}</td><td>{{ number_format($item->hourly_pay_amount) }}</td><td>{{ number_format($item->overtime_pay_amount) }}</td><td><b>{{ number_format($item->payable_amount) }}</b></td></tr>@endforeach</tbody></table></div></section>
@endsection
@push('scripts')<script src="{{ asset('js/stage07-clinical.js').'?v=0.19.0' }}"></script>@endpush
