<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up():void {
  Schema::table('appointments',function(Blueprint $t){$t->timestamp('checked_in_at')->nullable()->after('status');$t->foreignId('checked_in_by')->nullable()->after('checked_in_at')->constrained('users')->nullOnDelete();$t->timestamp('session_started_at')->nullable()->after('checked_in_by');$t->timestamp('session_ended_at')->nullable()->after('session_started_at');$t->timestamp('no_show_at')->nullable()->after('session_ended_at');});
  Schema::create('appointment_waitlists',function(Blueprint $t){$t->id();$t->foreignId('centre_id')->constrained()->cascadeOnDelete();$t->foreignId('client_id')->constrained()->cascadeOnDelete();$t->foreignId('topic_id')->constrained('service_topics')->cascadeOnDelete();$t->foreignId('counselor_id')->nullable()->constrained('users')->nullOnDelete();$t->dateTime('desired_from')->nullable();$t->dateTime('desired_until')->nullable();$t->unsignedTinyInteger('priority')->default(0);$t->string('status',20)->default('waiting')->index();$t->text('notes')->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('promoted_at')->nullable();$t->foreignId('promoted_appointment_id')->nullable()->constrained('appointments')->nullOnDelete();$t->timestamps();$t->index(['centre_id','status','priority']);});
  Schema::create('appointment_reschedules',function(Blueprint $t){$t->id();$t->foreignId('centre_id')->constrained()->cascadeOnDelete();$t->foreignId('from_appointment_id')->constrained('appointments')->cascadeOnDelete();$t->foreignId('to_appointment_id')->constrained('appointments')->cascadeOnDelete();$t->foreignId('client_id')->constrained()->cascadeOnDelete();$t->text('reason')->nullable();$t->foreignId('changed_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
  Schema::create('telephone_consultations',function(Blueprint $t){$t->id();$t->foreignId('centre_id')->constrained()->cascadeOnDelete();$t->foreignId('client_id')->constrained()->cascadeOnDelete();$t->foreignId('appointment_id')->nullable()->constrained('appointments')->nullOnDelete();$t->foreignId('counselor_id')->nullable()->constrained('users')->nullOnDelete();$t->string('phone_number',32);$t->dateTime('started_at');$t->dateTime('ended_at')->nullable();$t->string('status',20)->default('scheduled')->index();$t->text('outcome')->nullable();$t->text('counselor_note')->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->index(['centre_id','started_at']);});
  Schema::create('sms_messages',function(Blueprint $t){$t->id();$t->foreignId('centre_id')->constrained()->cascadeOnDelete();$t->foreignId('client_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('appointment_id')->nullable()->constrained('appointments')->nullOnDelete();$t->string('phone_number',32);$t->string('type',40);$t->text('body');$t->dateTime('scheduled_for')->nullable();$t->dateTime('sent_at')->nullable();$t->string('status',20)->default('queued')->index();$t->text('provider_response')->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->unique(['appointment_id','type'],'sms_appointment_type_unique');$t->index(['centre_id','status','scheduled_for']);});
 }
 public function down():void {Schema::dropIfExists('sms_messages');Schema::dropIfExists('telephone_consultations');Schema::dropIfExists('appointment_reschedules');Schema::dropIfExists('appointment_waitlists');Schema::table('appointments',function(Blueprint $t){$t->dropConstrainedForeignId('checked_in_by');$t->dropColumn(['checked_in_at','session_started_at','session_ended_at','no_show_at']);});}
};
