<?php

return [
    'roles' => [
        'super_admin' => 'ادمین سیستم',
        'manager' => 'مدیر مرکز مشاوره',
        'secretary' => 'منشی',
        'counselor' => 'مشاور',
        'test_manager' => 'مسئول تست',
        'client' => 'مراجعه‌کننده',
    ],
    'role_colors' => [
        'super_admin' => 'danger', 'manager' => 'primary', 'secretary' => 'success',
        'counselor' => 'warning', 'test_manager' => 'info', 'client' => 'slate',
    ],
    'menus' => [
        'common' => [
            ['label' => 'داشبورد', 'slug' => 'dashboard', 'icon' => 'ki-filled ki-home-2'],
            ['label' => 'پروفایل من', 'slug' => 'profile', 'icon' => 'ki-filled ki-profile-circle'],
            ['label' => 'اعلان‌ها', 'slug' => 'notifications', 'icon' => 'ki-filled ki-notification-on', 'fake' => true],
            ['label' => 'گفتگو و چت', 'slug' => 'chat', 'icon' => 'ki-filled ki-messages', 'fake' => true],
        ],
        'super_admin' => [
            ['section' => 'مدیریت سامانه'],
            ['label' => 'مدیریت کاربران', 'slug' => 'users', 'icon' => 'ki-filled ki-people'],
            ['label' => 'نقش‌ها و دسترسی‌ها', 'slug' => 'roles', 'icon' => 'ki-filled ki-security-user'],
            ['label' => 'کاتالوگ مجوزها', 'slug' => 'permissions', 'icon' => 'ki-filled ki-shield-search'],
            ['label' => 'فرمساز مشخصات پروفایل', 'slug' => 'profile-fields', 'icon' => 'ki-filled ki-setting-2'],
            ['label' => 'مرکزها و تنظیمات', 'slug' => 'centres', 'icon' => 'ki-filled ki-setting-4'],
            ['section' => 'پایش و امنیت'],
            ['label' => 'پایش سیستم', 'slug' => 'monitoring', 'icon' => 'ki-filled ki-chart-line-up'],
            ['label' => 'لاگ‌ها و رویدادها', 'slug' => 'audit-logs', 'icon' => 'ki-filled ki-notepad'],
            ['label' => 'گزارش‌های سامانه', 'slug' => 'reports', 'icon' => 'ki-filled ki-document'],
        ],
        'manager' => [
            ['section' => 'مدیریت مرکز'],
            ['label' => 'کاربران مرکز', 'slug' => 'users', 'icon' => 'ki-filled ki-people'],
            ['label' => 'موضوعات و تعرفه', 'slug' => 'centre-operations', 'icon' => 'ki-filled ki-calendar-tick'],
            ['label' => 'کارکنان', 'slug' => 'staff', 'icon' => 'ki-filled ki-profile-user'],
            ['label' => 'شعب مرکز', 'slug' => 'branches', 'icon' => 'ki-filled ki-geolocation'],
            ['label' => 'تنظیمات مرکز', 'slug' => 'centre-settings', 'icon' => 'ki-filled ki-setting-4'],
            ['label' => 'روزها و ساعات کاری', 'slug' => 'work-hours', 'icon' => 'ki-filled ki-calendar-tick'],
            ['label' => 'تعرفه و دستمزد', 'slug' => 'fees', 'icon' => 'ki-filled ki-dollar'],
            ['label' => 'نوبت‌ها و تقویم', 'slug' => 'appointments', 'icon' => 'ki-filled ki-calendar-8'],
            ['section' => 'عملکرد'],
            ['label' => 'گزارش مرکز', 'slug' => 'centre-reports', 'icon' => 'ki-filled ki-chart-simple'],
            ['label' => 'پیام‌ها', 'slug' => 'messages', 'icon' => 'ki-filled ki-messages'],
        ],
        'secretary' => [
            ['section' => 'عملیات منشی'],
            ['label' => 'کارکنان مرکز', 'slug' => 'staff', 'icon' => 'ki-filled ki-profile-user'],
            ['label' => 'شعب مرکز', 'slug' => 'branches', 'icon' => 'ki-filled ki-geolocation'],
            ['label' => 'روزها و ساعات کاری', 'slug' => 'work-hours', 'icon' => 'ki-filled ki-calendar-tick'],
            ['label' => 'تعطیلات مرکز', 'slug' => 'holidays', 'icon' => 'ki-filled ki-calendar-8'],
            ['label' => 'مرخصی مشاوران', 'slug' => 'leaves', 'icon' => 'ki-filled ki-calendar-remove'],
            ['label' => 'تقویم نوبت‌ها', 'slug' => 'appointments', 'icon' => 'ki-filled ki-calendar-8'],
            ['label' => 'مراجعین', 'slug' => 'clients', 'icon' => 'ki-filled ki-people'],
            ['label' => 'پرونده‌های مراجعین', 'slug' => 'records', 'icon' => 'ki-filled ki-folder'],
            ['label' => 'ثبت نوبت جدید', 'slug' => 'new-appointment', 'icon' => 'ki-filled ki-plus'],
            ['label' => 'پرداخت‌ها', 'slug' => 'payments', 'icon' => 'ki-filled ki-wallet'],
            ['label' => 'پیام‌ها', 'slug' => 'messages', 'icon' => 'ki-filled ki-messages'],
        ],
        'counselor' => [
            ['section' => 'پنل مشاور'],
            ['label' => 'تقویم من', 'slug' => 'my-calendar', 'icon' => 'ki-filled ki-calendar-8'],
            ['label' => 'نوبت‌های من', 'slug' => 'my-appointments', 'icon' => 'ki-filled ki-calendar-tick'],
            ['label' => 'پرونده مراجعین', 'slug' => 'client-records', 'icon' => 'ki-filled ki-folder'],
            ['label' => 'یادداشت‌های مشاوره', 'slug' => 'notes', 'icon' => 'ki-filled ki-notepad'],
            ['label' => 'آزمون‌های ارجاع‌شده', 'slug' => 'assigned-tests', 'icon' => 'ki-filled ki-notepad-edit'],
            ['label' => 'درآمد و کارکرد', 'slug' => 'earnings', 'icon' => 'ki-filled ki-chart-line-up'],
        ],
        'test_manager' => [
            ['section' => 'مدیریت آزمون‌ها'],
            ['label' => 'بانک تست‌ها', 'slug' => 'test-bank', 'icon' => 'ki-filled ki-book-open'],
            ['label' => 'دسته‌بندی تست‌ها', 'slug' => 'test-categories', 'icon' => 'ki-filled ki-category'],
            ['label' => 'اختصاص تست به مراجع', 'slug' => 'assign-tests', 'icon' => 'ki-filled ki-send'],
            ['label' => 'نتایج آزمون‌ها', 'slug' => 'test-results', 'icon' => 'ki-filled ki-chart-simple'],
            ['label' => 'گزارش‌ها', 'slug' => 'test-reports', 'icon' => 'ki-filled ki-document'],
        ],
        'client' => [
            ['section' => 'پنل مراجعه‌کننده'],
            ['label' => 'نوبت‌های من', 'slug' => 'my-appointments', 'icon' => 'ki-filled ki-calendar-tick'],
            ['label' => 'پرونده من', 'slug' => 'my-record', 'icon' => 'ki-filled ki-folder'],
            ['label' => 'آزمون‌های من', 'slug' => 'my-tests', 'icon' => 'ki-filled ki-notepad-edit'],
            ['label' => 'پرداخت‌های من', 'slug' => 'my-payments', 'icon' => 'ki-filled ki-wallet'],
        ],
    ],
    'permission_menus' => [
        ['label' => 'مدیریت کاربران', 'slug' => 'users', 'icon' => 'ki-filled ki-people', 'permission' => 'users.view'],
        ['label' => 'نقش‌ها و دسترسی‌ها', 'slug' => 'roles', 'icon' => 'ki-filled ki-security-user', 'permission' => 'roles.view'],
        ['label' => 'کاتالوگ مجوزها', 'slug' => 'permissions', 'icon' => 'ki-filled ki-shield-search', 'permission' => 'permissions.view'],
        ['label' => 'فرمساز مشخصات پروفایل', 'slug' => 'profile-fields', 'icon' => 'ki-filled ki-setting-2', 'permission' => 'profile_fields.manage'],
        ['label' => 'مرکزها و تنظیمات', 'slug' => 'centres', 'icon' => 'ki-filled ki-setting-4', 'permission' => 'centres.view'],
        ['label' => 'کارکنان', 'slug' => 'staff', 'icon' => 'ki-filled ki-profile-user', 'permission' => 'staff.view'],
        ['label' => 'شعب مرکز', 'slug' => 'branches', 'icon' => 'ki-filled ki-geolocation', 'permission' => 'branches.view'],
        ['label' => 'تنظیمات مرکز', 'slug' => 'centre-settings', 'icon' => 'ki-filled ki-setting-4', 'permission' => 'centre_settings.view'],
        ['label' => 'ساعات کاری مشاورین', 'slug' => 'work-hours', 'icon' => 'ki-filled ki-calendar-tick', 'permission' => 'schedules.view'],
        ['label' => 'تعرفه و دستمزد', 'slug' => 'fees', 'icon' => 'ki-filled ki-dollar', 'permission' => 'fees.view'],
        ['label' => 'نوبت‌ها و تقویم', 'slug' => 'appointments', 'icon' => 'ki-filled ki-calendar-8', 'permission' => 'appointments.view'],
        ['label' => 'پایش سیستم', 'slug' => 'monitoring', 'icon' => 'ki-filled ki-chart-line-up', 'permission' => 'monitoring.view'],
        ['label' => 'لاگ‌ها و رویدادها', 'slug' => 'audit-logs', 'icon' => 'ki-filled ki-notepad', 'permission' => 'audit_logs.view'],
        ['label' => 'گزارش‌های سامانه', 'slug' => 'reports', 'icon' => 'ki-filled ki-document', 'permission' => 'reports.view'],
    ],
];
