<?php

return [
    'roles' => [
        'super_admin' => 'ادمین سیستم',
        'manager' => 'مدیر مرکز مشاوره',
        'secretary' => 'منشی',
        'finance' => 'مسئول مالی',
        'counselor' => 'مشاور',
        'test_manager' => 'مسئول تست',
        'client' => 'مراجعه‌کننده',
    ],
    'role_colors' => [
        'super_admin' => 'danger', 'manager' => 'primary', 'secretary' => 'success',
        'finance' => 'violet', 'counselor' => 'warning', 'test_manager' => 'info', 'client' => 'slate',
    ],
    // Curated primary navigation. Each link has a real GET route and an explicit role.
    // Sidebar additionally checks the effective permission of the active assignment.
    'menus' => [
        'common' => [
            ['label'=>'داشبورد','slug'=>'dashboard','route'=>'dashboard','icon'=>'ki-filled ki-home-2','permission'=>'dashboard.view'],
            ['label'=>'پروفایل من','slug'=>'profile','route'=>'profile.show','icon'=>'ki-filled ki-profile-circle'],
        ],
        'super_admin' => [
            ['section'=>'مدیریت سامانه'],
            ['label'=>'مدیریت کاربران','slug'=>'users','route'=>'users.index','permission'=>'users.view','icon'=>'ki-filled ki-people'],
            ['label'=>'نقش‌ها و دسترسی‌ها','slug'=>'roles','route'=>'roles.index','permission'=>'roles.view','icon'=>'ki-filled ki-security-user'],
            ['label'=>'فرمساز مشخصات پروفایل','slug'=>'profile-fields','route'=>'profile-fields.index','permission'=>'profile_fields.manage','icon'=>'ki-filled ki-setting-2'],
            ['label'=>'مرکزها و تنظیمات','slug'=>'centres','route'=>'centres.index','permission'=>'centres.view','icon'=>'ki-filled ki-setting-4'],
        ],
        'manager' => [
            ['section'=>'مدیریت مرکز'],
            ['label'=>'کاربران مرکز','slug'=>'users','route'=>'users.index','permission'=>'users.view','icon'=>'ki-filled ki-people'],
            ['label'=>'کارکنان','slug'=>'staff','route'=>'staff.index','permission'=>'staff.view','icon'=>'ki-filled ki-profile-user'],
            ['label'=>'مراجعین','slug'=>'clients','route'=>'clients.index','permission'=>'clients.view','icon'=>'ki-filled ki-people'],
            ['label'=>'پرونده‌های مشاوره','slug'=>'cases','route'=>'cases.index','permission'=>'cases.view','icon'=>'ki-filled ki-folder'],
            ['label'=>'مراجعین تکراری','slug'=>'client-duplicates','route'=>'clients.duplicates','permission'=>'clients.duplicates','icon'=>'ki-filled ki-search-list'],
            ['label'=>'شعب مرکز','slug'=>'branches','route'=>'centres.branches.index','centre'=>true,'permission'=>'branches.view','icon'=>'ki-filled ki-geolocation'],
            ['label'=>'تنظیمات مرکز','slug'=>'centre-settings','route'=>'centres.settings.edit','centre'=>true,'permission'=>'centre_settings.view','icon'=>'ki-filled ki-setting-4'],
            ['section'=>'نوبت‌دهی'],
            ['label'=>'موضوعات و تعرفه','slug'=>'centre-operations','route'=>'centres.topics','centre'=>true,'permission'=>'fees.view','icon'=>'ki-filled ki-calendar-tick'],
            ['label'=>'روزها و ساعات کاری','slug'=>'work-hours','route'=>'centres.work-hours','centre'=>true,'permission'=>'schedules.view','icon'=>'ki-filled ki-calendar-tick'],
            ['label'=>'تعطیلات مرکز','slug'=>'holidays','route'=>'centres.holidays','centre'=>true,'permission'=>'schedules.view','icon'=>'ki-filled ki-calendar-8'],
            ['label'=>'مرخصی مشاوران','slug'=>'leaves','route'=>'centres.leaves','centre'=>true,'permission'=>'schedules.view','icon'=>'ki-filled ki-calendar-remove'],
            ['label'=>'اتاق‌ها','slug'=>'rooms','route'=>'centres.rooms','centre'=>true,'permission'=>'schedules.view','icon'=>'ki-filled ki-home-2'],
            ['label'=>'نوبت‌ها و تقویم','slug'=>'appointments','route'=>'appointments.index','permission'=>'appointments.view','icon'=>'ki-filled ki-calendar-8'],
            ['label'=>'عملیات روزانه','slug'=>'operations','route'=>'operations.index','permission'=>'appointments.manage','icon'=>'ki-filled ki-check-circle'],
            ['label'=>'تنظیمات نوبت‌دهی','slug'=>'appointments-settings','route'=>'centres.appointments-settings.index','centre'=>true,'permission'=>'appointments.manage','icon'=>'ki-filled ki-setting-2'],
            ['section'=>'مالی'],
            ['label'=>'صندوق و دریافت‌ها','slug'=>'finance-cashier','route'=>'finance.cashier.index','permission'=>'payments.view','icon'=>'ki-filled ki-wallet'],
            ['label'=>'قوانین سهم مشاور','slug'=>'compensation-rules','route'=>'centres.compensation-rules.index','centre'=>true,'permission'=>'compensation_rules.view','icon'=>'ki-filled ki-percentage'],
            ['label'=>'تسویه مشاوران','slug'=>'settlements','route'=>'settlements.index','permission'=>'settlements.view','icon'=>'ki-filled ki-cheque'],
        ],
        'secretary' => [
            ['section'=>'عملیات منشی'],
            ['label'=>'تقویم نوبت‌ها','slug'=>'appointments','route'=>'appointments.calendar','permission'=>'appointments.view','icon'=>'ki-filled ki-calendar-8'],
            ['label'=>'عملیات روزانه','slug'=>'operations','route'=>'operations.index','permission'=>'appointments.manage','icon'=>'ki-filled ki-check-circle'],
            ['label'=>'مراجعین و پرونده‌ها','slug'=>'clients','route'=>'clients.index','permission'=>'clients.view','icon'=>'ki-filled ki-people'],
            ['label'=>'پرونده‌های مشاوره','slug'=>'cases','route'=>'cases.index','permission'=>'cases.view','icon'=>'ki-filled ki-folder'],
            ['label'=>'مراجعین تکراری','slug'=>'client-duplicates','route'=>'clients.duplicates','permission'=>'clients.duplicates','icon'=>'ki-filled ki-search-list'],
            ['label'=>'کارکنان مرکز','slug'=>'staff','route'=>'staff.index','permission'=>'staff.view','icon'=>'ki-filled ki-profile-user'],
            ['label'=>'روزها و ساعات کاری','slug'=>'work-hours','route'=>'centres.work-hours','centre'=>true,'permission'=>'schedules.view','icon'=>'ki-filled ki-calendar-tick'],
            ['label'=>'تعطیلات مرکز','slug'=>'holidays','route'=>'centres.holidays','centre'=>true,'permission'=>'schedules.view','icon'=>'ki-filled ki-calendar-8'],
            ['label'=>'مرخصی مشاوران','slug'=>'leaves','route'=>'centres.leaves','centre'=>true,'permission'=>'schedules.view','icon'=>'ki-filled ki-calendar-remove'],
            ['label'=>'اتاق‌ها','slug'=>'rooms','route'=>'centres.rooms','centre'=>true,'permission'=>'schedules.view','icon'=>'ki-filled ki-home-2'],
            ['label'=>'حضور و غیاب','slug'=>'attendance','route'=>'attendance.index','icon'=>'ki-filled ki-time'],
            ['label'=>'صندوق و دریافت‌ها','slug'=>'finance-cashier','route'=>'finance.cashier.index','permission'=>'payments.view','icon'=>'ki-filled ki-wallet'],
        ],
        'finance' => [
            ['section'=>'عملیات مالی'],
            ['label'=>'صندوق و دریافت‌ها','slug'=>'finance-cashier','route'=>'finance.cashier.index','permission'=>'payments.view','icon'=>'ki-filled ki-wallet'],
            ['label'=>'نوبت‌ها و مانده‌ها','slug'=>'appointments','route'=>'appointments.index','permission'=>'appointments.view','icon'=>'ki-filled ki-calendar-tick'],
            ['label'=>'مراجعین','slug'=>'clients','route'=>'clients.index','permission'=>'clients.view','icon'=>'ki-filled ki-people'],
            ['label'=>'قوانین سهم مشاور','slug'=>'compensation-rules','route'=>'centres.compensation-rules.index','centre'=>true,'permission'=>'compensation_rules.view','icon'=>'ki-filled ki-percentage'],
            ['label'=>'تسویه مشاوران','slug'=>'settlements','route'=>'settlements.index','permission'=>'settlements.view','icon'=>'ki-filled ki-cheque'],
        ],
        'counselor' => [
            ['section'=>'کار من'],
            ['label'=>'جلسات و گزارش‌های من','slug'=>'counselor-workspace','route'=>'counselor.workspace','permission'=>'session_reports.view','icon'=>'ki-filled ki-notepad-edit'],
            ['label'=>'تقویم و مرخصی من','slug'=>'my-calendar','route'=>'counselor.week','permission'=>'appointments.view','icon'=>'ki-filled ki-calendar-8'],
            ['label'=>'نوبت‌های من','slug'=>'my-appointments','route'=>'appointments.index','permission'=>'appointments.view','icon'=>'ki-filled ki-calendar-tick'],
            ['label'=>'پرونده‌های مشاوره','slug'=>'cases','route'=>'cases.index','permission'=>'cases.view','icon'=>'ki-filled ki-folder'],
            ['label'=>'حضور و غیاب','slug'=>'attendance','route'=>'attendance.index','icon'=>'ki-filled ki-time'],
            ['label'=>'تسویه‌های من','slug'=>'settlements','route'=>'settlements.index','permission'=>'settlements.view','icon'=>'ki-filled ki-cheque'],
        ],
        'test_manager' => [
            // Test pages are not yet implemented. Keep the navigation usable.
        ],
        'client' => [
            ['section'=>'حساب من'],
            ['label'=>'نوبت‌های من','slug'=>'my-appointments','route'=>'appointments.index','permission'=>'appointments.view','icon'=>'ki-filled ki-calendar-tick'],
        ],
    ],
    'permission_menus' => [
        ['label' => 'مدیریت کاربران', 'slug' => 'users', 'icon' => 'ki-filled ki-people', 'permission' => 'users.view'],
        ['label' => 'نقش‌ها و دسترسی‌ها', 'slug' => 'roles', 'icon' => 'ki-filled ki-security-user', 'permission' => 'roles.view'],
        ['label' => 'کاتالوگ مجوزها', 'slug' => 'permissions', 'icon' => 'ki-filled ki-shield-search', 'permission' => 'permissions.view'],
        ['label' => 'فرمساز مشخصات پروفایل', 'slug' => 'profile-fields', 'icon' => 'ki-filled ki-setting-2', 'permission' => 'profile_fields.manage'],
        ['label' => 'مرکزها و تنظیمات', 'slug' => 'centres', 'icon' => 'ki-filled ki-setting-4', 'permission' => 'centres.view'],
        ['label' => 'کارکنان', 'slug' => 'staff', 'icon' => 'ki-filled ki-profile-user', 'permission' => 'staff.view'],
        ['label' => 'مراجعین', 'slug' => 'clients', 'icon' => 'ki-filled ki-people', 'permission' => 'clients.view'],
        ['label' => 'پرونده‌های مشاوره', 'slug' => 'cases', 'icon' => 'ki-filled ki-folder', 'permission' => 'cases.view'],
        ['label' => 'تشخیص مراجع تکراری', 'slug' => 'client-duplicates', 'icon' => 'ki-filled ki-search-list', 'permission' => 'clients.duplicates'],
        ['label' => 'شعب مرکز', 'slug' => 'branches', 'icon' => 'ki-filled ki-geolocation', 'permission' => 'branches.view'],
        ['label' => 'تنظیمات مرکز', 'slug' => 'centre-settings', 'icon' => 'ki-filled ki-setting-4', 'permission' => 'centre_settings.view'],
        ['label' => 'ساعات کاری مشاورین', 'slug' => 'work-hours', 'icon' => 'ki-filled ki-calendar-tick', 'permission' => 'schedules.view'],
        ['label' => 'تعرفه و دستمزد', 'slug' => 'fees', 'icon' => 'ki-filled ki-dollar', 'permission' => 'fees.view'],
        ['label' => 'نوبت‌ها و تقویم', 'slug' => 'appointments', 'icon' => 'ki-filled ki-calendar-8', 'permission' => 'appointments.view'],
        ['label' => 'پایش سیستم', 'slug' => 'monitoring', 'icon' => 'ki-filled ki-chart-line-up', 'permission' => 'monitoring.view'],
        ['label' => 'لاگ‌ها و رویدادها', 'slug' => 'audit-logs', 'icon' => 'ki-filled ki-notepad', 'permission' => 'audit_logs.view'],
        ['label' => 'گزارش‌های سامانه', 'slug' => 'reports', 'icon' => 'ki-filled ki-document', 'permission' => 'reports.view'],
        ['label' => 'صندوق و دریافت‌ها', 'slug' => 'finance-cashier', 'icon' => 'ki-filled ki-wallet', 'permission' => 'payments.view'],
        ['label' => 'قوانین سهم مشاور', 'slug' => 'compensation-rules', 'icon' => 'ki-filled ki-percentage', 'permission' => 'compensation_rules.view'],
        ['label' => 'تسویه مشاوران', 'slug' => 'settlements', 'icon' => 'ki-filled ki-cheque', 'permission' => 'settlements.view'],
    ],
];
