<?php
/**
 * Plugin Name: Ensha Booking Connector
 * Description: Shortcode and Elementor-compatible Ensha appointment widget.
 * Version: 0.24.0
 */
if (!defined('ABSPATH')) exit;
add_action('admin_init',function(){register_setting('ensha_booking','ensha_booking_base_url');register_setting('ensha_booking','ensha_booking_centre_id');register_setting('ensha_booking','ensha_booking_api_key');});
add_action('admin_menu',function(){add_options_page('Ensha Booking','Ensha Booking','manage_options','ensha-booking',function(){?>
<div class="wrap"><h1>Ensha Booking</h1><form method="post" action="options.php"><?php settings_fields('ensha_booking');?><table class="form-table">
<tr><th>Ensha URL</th><td><input class="regular-text" name="ensha_booking_base_url" value="<?php echo esc_attr(get_option('ensha_booking_base_url'));?>" placeholder="https://srun.ir/ensha"></td></tr>
<tr><th>Centre ID</th><td><input name="ensha_booking_centre_id" value="<?php echo esc_attr(get_option('ensha_booking_centre_id'));?>"></td></tr>
<tr><th>API Key</th><td><input class="regular-text" type="password" name="ensha_booking_api_key" value="<?php echo esc_attr(get_option('ensha_booking_api_key'));?>"></td></tr></table><?php submit_button();?></form></div><?php });});
add_shortcode('ensha_booking',function(){if(!is_user_logged_in())return '<p>برای رزرو ابتدا وارد حساب شوید.</p>';$uid=get_current_user_id();$nonce=wp_create_nonce('ensha_booking_'.$uid);ob_start();?>
<form class="ensha-booking-widget" data-nonce="<?php echo esc_attr($nonce);?>"><label>از تاریخ<input type="date" name="from" required></label><label>تا تاریخ<input type="date" name="to" required></label><button type="button" data-load>نمایش زمان‌ها</button><select name="slot_id" data-slots required></select><button>ثبت نوبت</button><p data-result></p></form>
<script>(()=>{const f=document.currentScript.previousElementSibling,r=f.querySelector('[data-result]'),s=f.querySelector('[data-slots]');async function call(action,data){const x=await fetch('<?php echo esc_js(admin_url('admin-ajax.php'));?>',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({action,...data,nonce:f.dataset.nonce})});const j=await x.json();if(!j.success)throw new Error(j.data?.message||'خطا');return j.data}f.querySelector('[data-load]').onclick=async()=>{try{const j=await call('ensha_slots',{from:f.from.value,to:f.to.value});s.innerHTML=j.data.map(x=>`<option value="${x.id}">${x.start} — ${x.counselor.name}</option>`).join('')}catch(e){r.textContent=e.message}};f.onsubmit=async e=>{e.preventDefault();try{const j=await call('ensha_book',{slot_id:s.value});r.textContent='نوبت ثبت شد: '+j.number}catch(e){r.textContent=e.message}}})();</script><?php return ob_get_clean();});
function ensha_proxy($method,$path,$body=[]){$base=rtrim(get_option('ensha_booking_base_url'),'/');$centre=(int)get_option('ensha_booking_centre_id');return wp_remote_request($base.'/api/v1/centres/'.$centre.$path,['method'=>$method,'headers'=>['X-Ensha-Key'=>get_option('ensha_booking_api_key'),'Accept'=>'application/json'],'body'=>$body,'timeout'=>25]);}
add_action('wp_ajax_ensha_slots',function(){check_ajax_referer('ensha_booking_'.get_current_user_id(),'nonce');$r=ensha_proxy('GET','/availability?'.http_build_query(['from'=>sanitize_text_field($_POST['from']),'to'=>sanitize_text_field($_POST['to'])]));$j=json_decode(wp_remote_retrieve_body($r),true);wp_send_json_success($j);});
add_action('wp_ajax_ensha_book',function(){check_ajax_referer('ensha_booking_'.get_current_user_id(),'nonce');$u=wp_get_current_user();$r=ensha_proxy('POST','/appointments',['slot_id'=>(int)$_POST['slot_id'],'wordpress_user_id'=>(string)$u->ID,'first_name'=>$u->first_name?:$u->display_name,'last_name'=>$u->last_name?:'-','phone'=>get_user_meta($u->ID,'billing_phone',true),'email'=>$u->user_email]);$j=json_decode(wp_remote_retrieve_body($r),true);if(wp_remote_retrieve_response_code($r)>=300)wp_send_json_error($j,400);wp_send_json_success($j);});
