@extends('layouts.app', ['title'=>'شعب '.$centre->name])
@section('content')
@php($timezones = timezone_identifiers_list())
<div class="ensha-page-heading"><div><span class="ensha-eyebrow">ساختار مرکز</span><h2>شعب {{ $centre->name }}</h2><p>هر نقش مرکز‌محور می‌تواند به یک شعبه فعال متصل شود.</p></div><div class="ensha-quick-actions"><a class="ensha-secondary-btn" href="{{ route('centres.settings.edit',$centre) }}">تنظیمات مرکز</a><a class="ensha-secondary-btn" href="{{ route('centres.show',$centre) }}">بازگشت</a></div></div>
@if($errors->any())<div class="ensha-status danger">{{ $errors->first() }}</div>@endif
@if(session('success'))<div class="ensha-status success">{{ session('success') }}</div>@endif

@if(auth()->user()->hasPermission('branches.manage'))
<section class="ensha-card" style="padding:24px;margin-bottom:20px"><h3>افزودن شعبه</h3><form method="POST" action="{{ route('centres.branches.store',$centre) }}">@csrf
<div class="ensha-admin-grid"><label>نام شعبه <input class="kt-input" name="name" required maxlength="160" value="{{ old('name') }}"></label><label>کد شعبه <input class="kt-input" name="code" required maxlength="50" dir="ltr" value="{{ old('code') }}"></label><label>منطقه زمانی <select class="kt-input" name="timezone"><option value="">ارث‌بری از مرکز ({{ $centre->timezone }})</option>@foreach($timezones as $timezone)<option value="{{ $timezone }}" @selected(old('timezone')===$timezone)>{{ $timezone }}</option>@endforeach</select></label><label>تلفن <input class="kt-input" name="phone" maxlength="20" value="{{ old('phone') }}"></label><label>ایمیل <input class="kt-input" name="email" type="email" maxlength="190" value="{{ old('email') }}"></label><label>نشانی <input class="kt-input" name="address" maxlength="500" value="{{ old('address') }}"></label></div>
<div class="ensha-form-row"><label><input type="checkbox" name="is_active" value="1" checked> فعال</label><label><input type="checkbox" name="is_default" value="1"> شعبه پیش‌فرض</label></div><button class="ensha-primary-btn" type="submit">ثبت شعبه</button></form></section>
@endif

<div class="ensha-dashboard-grid">@forelse($branches as $branch)<section class="ensha-card" style="padding:24px"><div class="ensha-card-head"><div><span class="ensha-eyebrow">{{ $branch->is_default?'شعبه پیش‌فرض':'شعبه' }}</span><h3>{{ $branch->name }}</h3></div><span class="ensha-status {{ $branch->is_active?'success':'warning' }}">{{ $branch->is_active?'فعال':'غیرفعال' }}</span></div><p>کد: <b dir="ltr">{{ $branch->code }}</b> · {{ $branch->assignments_count }} انتساب</p><p>منطقه زمانی: <span dir="ltr">{{ $branch->effectiveTimezone() }}</span></p><p>{{ $branch->address ?: 'نشانی ثبت نشده' }}</p>
@if(auth()->user()->hasPermission('branches.manage'))<form method="POST" action="{{ route('centres.branches.update',[$centre,$branch]) }}">@csrf @method('PUT')<div class="ensha-admin-grid"><label>نام <input class="kt-input" name="name" required value="{{ $branch->name }}"></label><label>کد <input class="kt-input" name="code" required dir="ltr" value="{{ $branch->code }}"></label><label>منطقه زمانی <select class="kt-input" name="timezone"><option value="">ارث‌بری از مرکز</option>@foreach($timezones as $timezone)<option value="{{ $timezone }}" @selected($branch->timezone===$timezone)>{{ $timezone }}</option>@endforeach</select></label><label>تلفن <input class="kt-input" name="phone" value="{{ $branch->phone }}"></label><label>ایمیل <input class="kt-input" type="email" name="email" value="{{ $branch->email }}"></label><label>نشانی <input class="kt-input" name="address" value="{{ $branch->address }}"></label></div><div class="ensha-form-row"><label><input type="checkbox" name="is_active" value="1" @checked($branch->is_active)> فعال</label><label><input type="checkbox" name="is_default" value="1" @checked($branch->is_default)> پیش‌فرض</label></div><button class="ensha-secondary-btn" type="submit">ذخیره تغییرات</button></form>@endif
</section>@empty<section class="ensha-card" style="padding:24px">شعبه‌ای ثبت نشده است.</section>@endforelse</div>
@endsection
