@extends('layouts.app', ['title'=>'عملیات مرکز '.$centre->name])
@section('content')
<div class="ensha-page-heading"><div><h2>مدیریت {{ $centre->name }}</h2><p>موضوعات، مشاوران، برنامه هفتگی و ظرفیت حضوری</p></div><a class="ensha-secondary-btn" href="{{ route('staff.index') }}">فهرست مشاوران</a></div>
<div class="ensha-dashboard-grid">
<section class="ensha-card" style="padding:22px"><h3>دسته‌بندی موضوعی</h3><form method="POST" action="{{ route('centres.operations.category',$centre) }}">@csrf<label>عنوان دسته <input name="name" placeholder="طبی، مشاوره ..." required></label><button class="ensha-primary-btn">افزودن دسته</button></form><p>@foreach($categories as $category)<span class="ensha-badge-soft">{{ $category->name }}</span> @endforeach</p></section>
<section class="ensha-card" style="padding:22px"><h3>تعریف موضوع و تعرفه</h3><form method="POST" action="{{ route('centres.operations.topic',$centre) }}" class="ensha-form-grid">@csrf<label>دسته<select name="category_id" required>@foreach($categories as $c)<option value="{{ $c->id }}">{{ $c->name }}</option>@endforeach</select></label><label>موضوع<input name="name" required placeholder="مشاوره خانواده"></label><label>حداقل زمان (دقیقه)<input type="number" name="minimum_minutes" min="1" value="15" required></label><label>مدت جلسه (دقیقه)<input type="number" name="session_minutes" min="1" value="60" required></label><label>قیمت (تومان)<input type="number" name="price" min="0" required></label><label>رنگ<input type="color" name="color" value="#3b82f6"></label><button class="ensha-primary-btn">ثبت موضوع</button></form></section>
</div>
<section class="ensha-card" style="padding:22px"><h3>وضعیت مشاوران و عملکرد برنامه‌ریزی‌شده</h3><div class="ensha-table-wrap"><table class="ensha-table"><thead><tr><th>مشاور</th><th>وضعیت حساب</th><th>ساعت برنامه هفتگی</th><th>تعداد موضوع</th></tr></thead><tbody>@foreach($counselors as $c)<tr><td>{{ $c->display_name }}</td><td>{{ $c->isActive() ? 'فعال' : 'غیرفعال' }}</td><td>{{ round($shifts->where('user_id',$c->id)->sum(fn($shift)=>(strtotime($shift->ends_at)-strtotime($shift->starts_at))/3600),2) }} ساعت</td><td>{{ $topicAssignments->where('user_id',$c->id)->count() }}</td></tr>@endforeach</tbody></table></div><small>این آمار بر اساس برنامه و موضوعات ثبت‌شده است؛ نوبت‌های انجام‌شده هنوز در این نسخه ثبت نمی‌شوند.</small></section>
<section class="ensha-card" style="padding:22px"><h3>موضوعات و مدت جلسه</h3><div class="ensha-table-wrap"><table class="ensha-table"><thead><tr><th>دسته</th><th>موضوع</th><th>حداقل</th><th>جلسه</th><th>قیمت</th></tr></thead><tbody>@foreach($topics as $t)<tr><td>{{ $t->category_name }}</td><td><span style="display:inline-block;width:14px;height:14px;background:{{ $t->color }};border-radius:50%"></span> {{ $t->name }}</td><td colspan="3"><form method="POST" action="{{ route('centres.operations.topic.update',[$centre,$t->id]) }}" style="display:flex;gap:8px;align-items:center;flex-wrap:wrap">@csrf @method('PUT')<label>حداقل<input type="number" name="minimum_minutes" min="1" value="{{ $t->minimum_minutes }}" required style="width:85px"></label><label>جلسه<input type="number" name="session_minutes" min="1" value="{{ $t->session_minutes }}" required style="width:85px"></label><label>تومان<input type="number" name="price" min="0" value="{{ $t->price }}" required style="width:125px"></label><input type="color" name="color" value="{{ $t->color }}"><button class="ensha-secondary-btn">ذخیره</button></form></td></tr>@endforeach</tbody></table></div></section>
<section class="ensha-card" style="padding:22px"><h3>مشاوران مرکز</h3><p>برای افزودن مشاوری که در مرکز دیگری هم فعالیت دارد، کد ملی او را وارد کنید.</p><form method="POST" action="{{ route('centres.operations.counselor',$centre) }}">@csrf<label>کد ملی مشاور<input name="national_id" inputmode="numeric" maxlength="10" required></label><button class="ensha-primary-btn">افزودن مشاور موجود</button></form>@foreach($counselors as $c)<span class="ensha-badge-soft">{{ $c->display_name }}</span> @endforeach</section>
<section class="ensha-card" style="padding:22px"><h3>تخصیص چند موضوع به مشاور</h3><form method="POST" action="{{ route('centres.operations.assign',$centre) }}" id="ensha-topic-assignment">@csrf<label>مشاور<select name="user_id" required>@foreach($counselors as $c)<option value="{{ $c->id }}">{{ $c->display_name }}</option>@endforeach</select></label><div class="ensha-form-grid">@foreach($topics as $t)<label><input type="checkbox" name="topic_ids[]" value="{{ $t->id }}"> {{ $t->category_name }} / {{ $t->name }}</label>@endforeach</div><small>انتخاب‌های جدید برای مشاور انتخاب‌شده در این مرکز جایگزین موضوعات قبلی می‌شوند.</small><button class="ensha-primary-btn">ذخیره موضوعات مشاور</button></form></section>
<section class="ensha-card" style="padding:22px"><h3>برنامه هفتگی و دستمزد همکاری</h3><p>اگر زمان انتخابی با شیفت همین مشاور در مرکز دیگری تداخل داشته باشد، نام آن مرکز نمایش داده می‌شود.</p><form method="POST" action="{{ route('centres.operations.shift',$centre) }}" class="ensha-form-grid">@csrf<label>مشاور<select name="user_id" required>@foreach($counselors as $c)<option value="{{ $c->id }}">{{ $c->display_name }}</option>@endforeach</select></label><label>روز هفته<select name="weekday">@foreach(['شنبه','یکشنبه','دوشنبه','سه‌شنبه','چهارشنبه','پنجشنبه','جمعه'] as $i=>$day)<option value="{{ $i }}">{{ $day }}</option>@endforeach</select></label><label>از ساعت<input type="time" name="starts_at" required></label><label>تا ساعت<input type="time" name="ends_at" required></label><label>دستمزد ساعتی (تومان)<input type="number" name="hourly_pay" min="0" value="0" required></label><button class="ensha-primary-btn">ثبت شیفت</button></form><div class="ensha-table-wrap"><table class="ensha-table"><thead><tr><th>مشاور</th><th>روز</th><th>ساعت</th><th>مجموع</th><th>دستمزد ساعتی</th><th></th></tr></thead><tbody>@foreach($shifts as $s)<tr><td>{{ $s->first_name }} {{ $s->last_name }}</td><td>{{ ['شنبه','یکشنبه','دوشنبه','سه‌شنبه','چهارشنبه','پنجشنبه','جمعه'][$s->weekday] }}</td><td>{{ substr($s->starts_at,0,5) }} تا {{ substr($s->ends_at,0,5) }}</td><td>{{ round((strtotime($s->ends_at)-strtotime($s->starts_at))/3600,2) }} ساعت</td><td>{{ number_format($s->hourly_pay) }}</td><td><form method="POST" action="{{ route('centres.operations.shift.delete',[$centre,$s->id]) }}">@csrf @method('DELETE')<button class="ensha-secondary-btn">حذف</button></form></td></tr>@endforeach</tbody></table></div></section>
<div class="ensha-dashboard-grid"><section class="ensha-card" style="padding:22px"><h3>تعطیلات مرکز</h3><form method="POST" action="{{ route('centres.operations.closure',$centre) }}" class="ensha-form-grid">@csrf<label>از تاریخ<input type="date" name="starts_on" required></label><label>تا تاریخ<input type="date" name="ends_on" required></label><label>دلیل<input name="reason" required></label><button class="ensha-primary-btn">ثبت تعطیلی</button></form>@foreach($closures as $c)<p>{{ $c->starts_on }} تا {{ $c->ends_on }} · {{ $c->reason }}</p>@endforeach</section>
<section class="ensha-card" style="padding:22px"><h3>مرخصی مشاور</h3><form method="POST" action="{{ route('centres.operations.leave',$centre) }}" class="ensha-form-grid">@csrf<label>مشاور<select name="user_id">@foreach($counselors as $c)<option value="{{ $c->id }}">{{ $c->display_name }}</option>@endforeach</select></label><label>شروع<input type="datetime-local" name="starts_at" required></label><label>پایان<input type="datetime-local" name="ends_at" required></label><label>دلیل<input name="reason"></label><button class="ensha-primary-btn">ثبت مرخصی</button></form>@foreach($leaves as $l)<p>{{ $l->first_name }} {{ $l->last_name }} · {{ $l->starts_at }} تا {{ $l->ends_at }}</p>@endforeach</section></div>
<div class="ensha-dashboard-grid"><section class="ensha-card" style="padding:22px"><h3>اتاق‌های آماده فعالیت</h3><form method="POST" action="{{ route('centres.operations.room',$centre) }}">@csrf<label>نام اتاق<input name="name" required></label><button class="ensha-primary-btn">افزودن اتاق</button></form><p>ظرفیت هم‌زمان حضوری: {{ $rooms->where('is_active',1)->count() }} اتاق</p>@foreach($rooms as $room)<span class="ensha-badge-soft">{{ $room->name }}</span> @endforeach</section>
<section class="ensha-card" style="padding:22px"><h3>تاریخچه تغییر برنامه</h3>@forelse($history as $h)<p>{{ $h->first_name }} {{ $h->last_name }} · {{ $h->after ? 'ثبت' : 'حذف' }} · {{ $h->created_at }}</p>@empty<p>تغییری ثبت نشده است.</p>@endforelse</section></div>
@push('scripts')
<script>
(() => {
 const form=document.getElementById('ensha-topic-assignment');
 if(!form)return;
 const assigned=@json($topicMap);
 const select=form.querySelector('select[name="user_id"]');
 function refresh(){const ids=(assigned[select.value]||[]).map(String);form.querySelectorAll('input[name="topic_ids[]"]').forEach(el=>{el.checked=ids.includes(el.value)})}
 select.addEventListener('change',refresh);refresh();
})();
</script>
@endpush
@endsection
